package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseAccount;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Account extends BaseAccount<Account> {
	public static final Account dao = new Account().dao();
}
