package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseAccountInvitationRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AccountInvitationRecord extends BaseAccountInvitationRecord<AccountInvitationRecord> {
	public static final AccountInvitationRecord dao = new AccountInvitationRecord().dao();
}
