package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseAccountWechatRel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AccountWechatRel extends BaseAccountWechatRel<AccountWechatRel> {
	public static final AccountWechatRel dao = new AccountWechatRel().dao();
}
