package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseAccountinfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Accountinfo extends BaseAccountinfo<Accountinfo> {
	public static final Accountinfo dao = new Accountinfo().dao();
}
