package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseAgentUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AgentUser extends BaseAgentUser<AgentUser> {
	public static final AgentUser dao = new AgentUser().dao();
}
