package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseAgentArticle;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AgentArticle extends BaseAgentArticle<AgentArticle> {
	public static final AgentArticle dao = new AgentArticle().dao();
}
