package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseAgentLifeRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AgentLifeRecord extends BaseAgentLifeRecord<AgentLifeRecord> {
	public static final AgentLifeRecord dao = new AgentLifeRecord().dao();
}
