package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseAgentSchool;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AgentSchool extends BaseAgentSchool<AgentSchool> {
	public static final AgentSchool dao = new AgentSchool().dao();
}
