package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseAlbumAlias;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AlbumAlias extends BaseAlbumAlias<AlbumAlias> {
	public static final AlbumAlias dao = new AlbumAlias().dao();
}
