package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseAllMsg;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AllMsg extends BaseAllMsg<AllMsg> {
	public static final AllMsg dao = new AllMsg().dao();
}
