package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseApiLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ApiLog extends BaseApiLog<ApiLog> {
	public static final ApiLog dao = new ApiLog().dao();
}
