package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseApp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class App extends BaseApp<App> {
	public static final App dao = new App().dao();
}
