package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseAppFucShow;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AppFucShow extends BaseAppFucShow<AppFucShow> {
	public static final AppFucShow dao = new AppFucShow().dao();
}
