package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseAppindex;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Appindex extends BaseAppindex<Appindex> {
	public static final Appindex dao = new Appindex().dao();
}
