package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseApptime;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Apptime extends BaseApptime<Apptime> {
	public static final Apptime dao = new Apptime().dao();
}
