package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseArea;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Area extends BaseArea<Area> {
	public static final Area dao = new Area().dao();
}
