package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseArticle;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Article extends BaseArticle<Article> {
	public static final Article dao = new Article().dao();
}
