package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseAudioinfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Audioinfo extends BaseAudioinfo<Audioinfo> {
	public static final Audioinfo dao = new Audioinfo().dao();
}
