package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseBelong;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Belong extends BaseBelong<Belong> {
	public static final Belong dao = new Belong().dao();
}
