package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseBoneinUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BoneinUser extends BaseBoneinUser<BoneinUser> {
	public static final BoneinUser dao = new BoneinUser().dao();
}
