package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseBookshopOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BookshopOrder extends BaseBookshopOrder<BookshopOrder> {
	public static final BookshopOrder dao = new BookshopOrder().dao();
}
