package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseBookcollection;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Bookcollection extends BaseBookcollection<Bookcollection> {
	public static final Bookcollection dao = new Bookcollection().dao();
}
