package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseBookvehicle;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Bookvehicle extends BaseBookvehicle<Bookvehicle> {
	public static final Bookvehicle dao = new Bookvehicle().dao();
}
