package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseBooklabel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Booklabel extends BaseBooklabel<Booklabel> {
	public static final Booklabel dao = new Booklabel().dao();
}
