package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseBookshopBanner;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BookshopBanner extends BaseBookshopBanner<BookshopBanner> {
	public static final BookshopBanner dao = new BookshopBanner().dao();
}
