package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseBookshopOrderdetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BookshopOrderdetail extends BaseBookshopOrderdetail<BookshopOrderdetail> {
	public static final BookshopOrderdetail dao = new BookshopOrderdetail().dao();
}
