package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseBookCopy1;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BookCopy1 extends BaseBookCopy1<BookCopy1> {
	public static final BookCopy1 dao = new BookCopy1().dao();
}
