package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseBookShopUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BookShopUser extends BaseBookShopUser<BookShopUser> {
	public static final BookShopUser dao = new BookShopUser().dao();
}
