package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseBookorderinfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Bookorderinfo extends BaseBookorderinfo<Bookorderinfo> {
	public static final Bookorderinfo dao = new Bookorderinfo().dao();
}
