package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseBookkeyword;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Bookkeyword extends BaseBookkeyword<Bookkeyword> {
	public static final Bookkeyword dao = new Bookkeyword().dao();
}
