package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseBookshop;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Bookshop extends BaseBookshop<Bookshop> {
	public static final Bookshop dao = new Bookshop().dao();
}
