package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseBookcase;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Bookcase extends BaseBookcase<Bookcase> {
	public static final Bookcase dao = new Bookcase().dao();
}
