package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseBookShopCategory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BookShopCategory extends BaseBookShopCategory<BookShopCategory> {
	public static final BookShopCategory dao = new BookShopCategory().dao();
}
