package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseBulletinQuestion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BulletinQuestion extends BaseBulletinQuestion<BulletinQuestion> {
	public static final BulletinQuestion dao = new BulletinQuestion().dao();
}
