package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseBulletinQuestionAnswer;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BulletinQuestionAnswer extends BaseBulletinQuestionAnswer<BulletinQuestionAnswer> {
	public static final BulletinQuestionAnswer dao = new BulletinQuestionAnswer().dao();
}
