package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseCachfolder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Cachfolder extends BaseCachfolder<Cachfolder> {
	public static final Cachfolder dao = new Cachfolder().dao();
}
