package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseCareSignIn;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CareSignIn extends BaseCareSignIn<CareSignIn> {
	public static final CareSignIn dao = new CareSignIn().dao();
}
