package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseCareFeedback;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CareFeedback extends BaseCareFeedback<CareFeedback> {
	public static final CareFeedback dao = new CareFeedback().dao();
}
