package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseCategory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Category extends BaseCategory<Category> {
	public static final Category dao = new Category().dao();
}
