package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseCategoryCopy;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CategoryCopy extends BaseCategoryCopy<CategoryCopy> {
	public static final CategoryCopy dao = new CategoryCopy().dao();
}
