package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseCategorylabelCopy;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CategorylabelCopy extends BaseCategorylabelCopy<CategorylabelCopy> {
	public static final CategorylabelCopy dao = new CategorylabelCopy().dao();
}
