package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseChaozhiOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ChaozhiOrder extends BaseChaozhiOrder<ChaozhiOrder> {
	public static final ChaozhiOrder dao = new ChaozhiOrder().dao();
}
