package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseChaozhiStudyFriend;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ChaozhiStudyFriend extends BaseChaozhiStudyFriend<ChaozhiStudyFriend> {
	public static final ChaozhiStudyFriend dao = new ChaozhiStudyFriend().dao();
}
