package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseCity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class City extends BaseCity<City> {
	public static final City dao = new City().dao();
}
