package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseClassRoomReply;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ClassRoomReply extends BaseClassRoomReply<ClassRoomReply> {
	public static final ClassRoomReply dao = new ClassRoomReply().dao();

    public List<ClassRoomReply> findByStudentWithClassRoom(int studentId, int classRoomId) {
        return find("select * from class_room_reply where  student_id=? and class_room_id=?",studentId,classRoomId);
    }
}
