package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseClassRoomProductRel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ClassRoomProductRel extends BaseClassRoomProductRel<ClassRoomProductRel> {
	public static final ClassRoomProductRel dao = new ClassRoomProductRel().dao();
}
