package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseClassroomPackageRel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ClassroomPackageRel extends BaseClassroomPackageRel<ClassroomPackageRel> {
	public static final ClassroomPackageRel dao = new ClassroomPackageRel().dao();
}
