package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseClassRoomGradesRela;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ClassRoomGradesRela extends BaseClassRoomGradesRela<ClassRoomGradesRela> {
	public static final ClassRoomGradesRela dao = new ClassRoomGradesRela().dao();
}
