package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseClassLiveBooking;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ClassLiveBooking extends BaseClassLiveBooking<ClassLiveBooking> {
    public static final ClassLiveBooking dao = new ClassLiveBooking().dao();


}
