package com.wechat.jfinal.model;

import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Record;
import com.wechat.jfinal.model.base.BaseClassStudent;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ClassStudent extends BaseClassStudent<ClassStudent> {
	public static final ClassStudent dao = new ClassStudent().dao();


    public ClassStudent findStudentInfo(Integer studentId) {
        return  findFirst("select b.avatar,b.`name` from class_student b where  b.id=?",studentId);
    }
}
