package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseClassScriptGroupToType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ClassScriptGroupToType extends BaseClassScriptGroupToType<ClassScriptGroupToType> {
	public static final ClassScriptGroupToType dao = new ClassScriptGroupToType().dao();
}
