package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseClassCourseRecordOfStudent;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ClassCourseRecordOfStudent extends BaseClassCourseRecordOfStudent<ClassCourseRecordOfStudent> {
	public static final ClassCourseRecordOfStudent dao = new ClassCourseRecordOfStudent().dao();
}
