package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseClassCourseSchedule;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ClassCourseSchedule extends BaseClassCourseSchedule<ClassCourseSchedule> {
	public static final ClassCourseSchedule dao = new ClassCourseSchedule().dao();

    public List<ClassCourseSchedule> findDoDayByStudent(int studentId) {
        return find("SELECT class_grades_id,class_course_id,do_day FROM class_course_schedule WHERE student_id = ?",studentId);
    }
}
