package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseClassRoomWordsFilter;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ClassRoomWordsFilter extends BaseClassRoomWordsFilter<ClassRoomWordsFilter> {
	public static final ClassRoomWordsFilter dao = new ClassRoomWordsFilter().dao();
}
