package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseClassTeacher;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ClassTeacher extends BaseClassTeacher<ClassTeacher> {
	public static final ClassTeacher dao = new ClassTeacher().dao();

    public ClassTeacher findTeacherInfo(Integer teacherId) {
        return  findFirst("select b.avatar,b.`name` from class_teacher b where  b.id=?",teacherId);
    }
}
