package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseClassRoomLike;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ClassRoomLike extends BaseClassRoomLike<ClassRoomLike> {
	public static final ClassRoomLike dao = new ClassRoomLike().dao();
}
