package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseClassRoomRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ClassRoomRecord extends BaseClassRoomRecord<ClassRoomRecord> {
	public static final ClassRoomRecord dao = new ClassRoomRecord().dao();
}
