package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseClassRoomSign;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ClassRoomSign extends BaseClassRoomSign<ClassRoomSign> {
	public static final ClassRoomSign dao = new ClassRoomSign().dao();
}
