package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseClassCourseRecordAllIntegral;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ClassCourseRecordAllIntegral extends BaseClassCourseRecordAllIntegral<ClassCourseRecordAllIntegral> {
	public static final ClassCourseRecordAllIntegral dao = new ClassCourseRecordAllIntegral().dao();
}
