package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseClassGradesRela;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ClassGradesRela extends BaseClassGradesRela<ClassGradesRela> {
	public static final ClassGradesRela dao = new ClassGradesRela().dao();


    public void  findGradeByTeacherAndStudentId(String teacherId, String studentId) {

        ClassGradesRela first = findFirst("select * from class_grades_rela where teacherId=? and studentId=?", teacherId, studentId);


    }
}
