package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseClassCourseErrorWord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ClassCourseErrorWord extends BaseClassCourseErrorWord<ClassCourseErrorWord> {
	public static final ClassCourseErrorWord dao = new ClassCourseErrorWord().dao();
}
