package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseClassPackageOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ClassPackageOrder extends BaseClassPackageOrder<ClassPackageOrder> {
	public static final ClassPackageOrder dao = new ClassPackageOrder().dao();
}
