package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseClassTeacherGrades;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ClassTeacherGrades extends BaseClassTeacherGrades<ClassTeacherGrades> {
	public static final ClassTeacherGrades dao = new ClassTeacherGrades().dao();
}
