package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseClassRoomLabelRela;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ClassRoomLabelRela extends BaseClassRoomLabelRela<ClassRoomLabelRela> {
	public static final ClassRoomLabelRela dao = new ClassRoomLabelRela().dao();
}
