package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseClassStudentCopy;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ClassStudentCopy extends BaseClassStudentCopy<ClassStudentCopy> {
	public static final ClassStudentCopy dao = new ClassStudentCopy().dao();
}
