package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseClassHourse;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ClassHourse extends BaseClassHourse<ClassHourse> {
	public static final ClassHourse dao = new ClassHourse().dao();
}
