package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseClassroomPackageGrades;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ClassroomPackageGrades extends BaseClassroomPackageGrades<ClassroomPackageGrades> {
	public static final ClassroomPackageGrades dao = new ClassroomPackageGrades().dao();
}
