package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseClassCourseComment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ClassCourseComment extends BaseClassCourseComment<ClassCourseComment> {
	public static final ClassCourseComment dao = new ClassCourseComment().dao();
}
