package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseClassCourseRankingList;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ClassCourseRankingList extends BaseClassCourseRankingList<ClassCourseRankingList> {
	public static final ClassCourseRankingList dao = new ClassCourseRankingList().dao();
}
