package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseClassScriptDone;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ClassScriptDone extends BaseClassScriptDone<ClassScriptDone> {
	public static final ClassScriptDone dao = new ClassScriptDone().dao();
}
