package com.wechat.jfinal.model;

import java.util.List;

import com.wechat.jfinal.model.base.BaseClassroomPackage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ClassroomPackage extends BaseClassroomPackage<ClassroomPackage> {
	public static final ClassroomPackage dao = new ClassroomPackage().dao();
}
