package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseClassRoomReplyPic;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ClassRoomReplyPic extends BaseClassRoomReplyPic<ClassRoomReplyPic> {
	public static final ClassRoomReplyPic dao = new ClassRoomReplyPic().dao();

    public List<ClassRoomReplyPic> findByStudentWithClassRoom(int studentId, int classRoomId) {

        return  find("select a.* from class_room_reply_pic a, class_room_reply b  where b.class_room_id=? AND b.student_id=? and a.class_room_reply_id = b.id;",classRoomId,studentId);

    }
}
