package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseClassroomSubject;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ClassroomSubject extends BaseClassroomSubject<ClassroomSubject> {
	public static final ClassroomSubject dao = new ClassroomSubject().dao();
}
