package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseClassScriptType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ClassScriptType extends BaseClassScriptType<ClassScriptType> {
	public static final ClassScriptType dao = new ClassScriptType().dao();
}
