package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseClassCourseCopy1;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ClassCourseCopy1 extends BaseClassCourseCopy1<ClassCourseCopy1> {
	public static final ClassCourseCopy1 dao = new ClassCourseCopy1().dao();
}
