package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseClassScriptNormalVersion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ClassScriptNormalVersion extends BaseClassScriptNormalVersion<ClassScriptNormalVersion> {
	public static final ClassScriptNormalVersion dao = new ClassScriptNormalVersion().dao();
}
