package com.wechat.jfinal.model;

import java.util.ArrayList;
import java.util.List;

import com.wechat.jfinal.model.base.BaseClassCourse;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ClassCourse extends BaseClassCourse<ClassCourse> {
	public static final ClassCourse dao = new ClassCourse().dao();

	public List<ClassCourse> findByGrade(Integer classGradeId) {
		// TODO Auto-generated method stub
		return find("SELECT * FROM `class_course` WHERE class_grades_id = ? ORDER BY do_day ASC",classGradeId);
	}

    public List<ClassCourse> findByGradeIds(int[] gradeIds) {

		if (gradeIds == null || gradeIds.length ==0){
			return new ArrayList<ClassCourse>();
		}

		StringBuffer sql = new StringBuffer();

		sql.append("SELECT * FROM class_course WHERE class_grades_id IN (");

		for (int id : gradeIds) {
			sql.append(id + ",");
		}

		sql.deleteCharAt(sql.length() - 1);
		sql.append(");");

		return find(sql.toString());


	}

    public List<ClassCourse> findByGradeIdsWithReply(int[] gradeIds, int studentId) {

		if (gradeIds == null || gradeIds.length ==0){
			return new ArrayList<ClassCourse>();
		}

		StringBuffer sql = new StringBuffer();

		sql.append("SELECT *,IFNULL((SELECT id FROM lesson_script_reply WHERE class_course_id = c.id AND student_id = ? LIMIT 1),0) AS hasReply FROM class_course c WHERE c.class_grades_id IN (");

		for (int id : gradeIds) {
			sql.append(id + ",");
		}

		sql.deleteCharAt(sql.length() - 1);
		sql.append(");");

		return find(sql.toString(),studentId);

    }
}
