package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseCoinGift;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CoinGift extends BaseCoinGift<CoinGift> {
	public static final CoinGift dao = new CoinGift().dao();
}
