package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseCoupons;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Coupons extends BaseCoupons<Coupons> {
	public static final Coupons dao = new Coupons().dao();
}
