package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseCoursePeriod;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CoursePeriod extends BaseCoursePeriod<CoursePeriod> {
	public static final CoursePeriod dao = new CoursePeriod().dao();
}
