package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseCoursePlanInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CoursePlanInfo extends BaseCoursePlanInfo<CoursePlanInfo> {
	public static final CoursePlanInfo dao = new CoursePlanInfo().dao();
}
