package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseCourseScheduleNow;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CourseScheduleNow extends BaseCourseScheduleNow<CourseScheduleNow> {
	public static final CourseScheduleNow dao = new CourseScheduleNow().dao();
}
