package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseCourseWordToLabel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CourseWordToLabel extends BaseCourseWordToLabel<CourseWordToLabel> {
	public static final CourseWordToLabel dao = new CourseWordToLabel().dao();
}
