package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseCourseBooklib;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CourseBooklib extends BaseCourseBooklib<CourseBooklib> {
	public static final CourseBooklib dao = new CourseBooklib().dao();
}
