package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseCourse;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Course extends BaseCourse<Course> {
	public static final Course dao = new Course().dao();
}
