package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseCourseCopy;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CourseCopy extends BaseCourseCopy<CourseCopy> {
	public static final CourseCopy dao = new CourseCopy().dao();
}
