package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseDailyRecommendTag;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DailyRecommendTag extends BaseDailyRecommendTag<DailyRecommendTag> {
	public static final DailyRecommendTag dao = new DailyRecommendTag().dao();
}
