package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseDeskCapture;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DeskCapture extends BaseDeskCapture<DeskCapture> {
	public static final DeskCapture dao = new DeskCapture().dao();
}
