package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseDeviceFile;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DeviceFile extends BaseDeviceFile<DeviceFile> {
	public static final DeviceFile dao = new DeviceFile().dao();
}
