package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseDeviceTest;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DeviceTest extends BaseDeviceTest<DeviceTest> {
	public static final DeviceTest dao = new DeviceTest().dao();
}
