package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseDeviceSoundQuestionAnswer;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DeviceSoundQuestionAnswer extends BaseDeviceSoundQuestionAnswer<DeviceSoundQuestionAnswer> {
	public static final DeviceSoundQuestionAnswer dao = new DeviceSoundQuestionAnswer().dao();
}
