package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseDeviceDownloadRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DeviceDownloadRecord extends BaseDeviceDownloadRecord<DeviceDownloadRecord> {
	public static final DeviceDownloadRecord dao = new DeviceDownloadRecord().dao();
}
