package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseDeviceProperty;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DeviceProperty extends BaseDeviceProperty<DeviceProperty> {
	public static final DeviceProperty dao = new DeviceProperty().dao();
}
