package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseDeviceOnlineRecordCount;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DeviceOnlineRecordCount extends BaseDeviceOnlineRecordCount<DeviceOnlineRecordCount> {
	public static final DeviceOnlineRecordCount dao = new DeviceOnlineRecordCount().dao();
}
