package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseDeviceLiber;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DeviceLiber extends BaseDeviceLiber<DeviceLiber> {
	public static final DeviceLiber dao = new DeviceLiber().dao();
}
