package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseDeviceSchedule;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DeviceSchedule extends BaseDeviceSchedule<DeviceSchedule> {
	public static final DeviceSchedule dao = new DeviceSchedule().dao();

}
