package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseDeviceActivity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DeviceActivity extends BaseDeviceActivity<DeviceActivity> {
	public static final DeviceActivity dao = new DeviceActivity().dao();
}
