package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseDeviceOnlineRecordNew;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DeviceOnlineRecordNew extends BaseDeviceOnlineRecordNew<DeviceOnlineRecordNew> {
	public static final DeviceOnlineRecordNew dao = new DeviceOnlineRecordNew().dao();
}
