package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseDevice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Device extends BaseDevice<Device> {
	public static final Device dao = new Device().dao();
}
