package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseDeviceAgentRelation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DeviceAgentRelation extends BaseDeviceAgentRelation<DeviceAgentRelation> {
	public static final DeviceAgentRelation dao = new DeviceAgentRelation().dao();
}
