package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseDeviceStudentSchool;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DeviceStudentSchool extends BaseDeviceStudentSchool<DeviceStudentSchool> {
	public static final DeviceStudentSchool dao = new DeviceStudentSchool().dao();
}
