package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseDeviceTransportList;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DeviceTransportList extends BaseDeviceTransportList<DeviceTransportList> {
	public static final DeviceTransportList dao = new DeviceTransportList().dao();
}
