package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseDiscovery;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Discovery extends BaseDiscovery<Discovery> {
	public static final Discovery dao = new Discovery().dao();
}
