package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseDriver;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Driver extends BaseDriver<Driver> {
	public static final Driver dao = new Driver().dao();
}
