package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseElectrismorder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Electrismorder extends BaseElectrismorder<Electrismorder> {
	public static final Electrismorder dao = new Electrismorder().dao();
}
