package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseEovaUserInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EovaUserInfo extends BaseEovaUserInfo<EovaUserInfo> {
	public static final EovaUserInfo dao = new EovaUserInfo().dao();
}
