package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseEovaUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EovaUser extends BaseEovaUser<EovaUser> {
	public static final EovaUser dao = new EovaUser().dao();
}
