package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseEpalsystem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Epalsystem extends BaseEpalsystem<Epalsystem> {
	public static final Epalsystem dao = new Epalsystem().dao();
}
