package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseEvalWxUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EvalWxUser extends BaseEvalWxUser<EvalWxUser> {
	public static final EvalWxUser dao = new EvalWxUser().dao();
}
