package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseEvalQuestion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EvalQuestion extends BaseEvalQuestion<EvalQuestion> {
	public static final EvalQuestion dao = new EvalQuestion().dao();
}
