package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseEvalOption;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EvalOption extends BaseEvalOption<EvalOption> {
	public static final EvalOption dao = new EvalOption().dao();
}
