package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseEvaluationTemplate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EvaluationTemplate extends BaseEvaluationTemplate<EvaluationTemplate> {
	public static final EvaluationTemplate dao = new EvaluationTemplate().dao();
}
