package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseExhibitionSign;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ExhibitionSign extends BaseExhibitionSign<ExhibitionSign> {
	public static final ExhibitionSign dao = new ExhibitionSign().dao();
}
