package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseFandouAgent;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FandouAgent extends BaseFandouAgent<FandouAgent> {
	public static final FandouAgent dao = new FandouAgent().dao();
}
