package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseFandouLibraryMember;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FandouLibraryMember extends BaseFandouLibraryMember<FandouLibraryMember> {
	public static final FandouLibraryMember dao = new FandouLibraryMember().dao();
}
