package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseFbmsUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FbmsUser extends BaseFbmsUser<FbmsUser> {
	public static final FbmsUser dao = new FbmsUser().dao();
}
