package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseFilecach;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Filecach extends BaseFilecach<Filecach> {
	public static final Filecach dao = new Filecach().dao();
}
