package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseFoodMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FoodMenu extends BaseFoodMenu<FoodMenu> {
	public static final FoodMenu dao = new FoodMenu().dao();
}
