package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseFoodMenuIngredientsRela;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FoodMenuIngredientsRela extends BaseFoodMenuIngredientsRela<FoodMenuIngredientsRela> {
	public static final FoodMenuIngredientsRela dao = new FoodMenuIngredientsRela().dao();
}
