package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseFreeLessonInviteRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FreeLessonInviteRecord extends BaseFreeLessonInviteRecord<FreeLessonInviteRecord> {
	public static final FreeLessonInviteRecord dao = new FreeLessonInviteRecord().dao();
}
