package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseGameintegar;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Gameintegar extends BaseGameintegar<Gameintegar> {
	public static final Gameintegar dao = new Gameintegar().dao();
}
