package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseGoodVideo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GoodVideo extends BaseGoodVideo<GoodVideo> {
	public static final GoodVideo dao = new GoodVideo().dao();
}
