package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseGradeCode;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GradeCode extends BaseGradeCode<GradeCode> {
	public static final GradeCode dao = new GradeCode().dao();
}
