package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseGradesTemporaryClass;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GradesTemporaryClass extends BaseGradesTemporaryClass<GradesTemporaryClass> {
	public static final GradesTemporaryClass dao = new GradesTemporaryClass().dao();
}
