package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseGroupChat;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GroupChat extends BaseGroupChat<GroupChat> {
	public static final GroupChat dao = new GroupChat().dao();
}
