package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseHistorySchedules;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class HistorySchedules extends BaseHistorySchedules<HistorySchedules> {
	public static final HistorySchedules dao = new HistorySchedules().dao();
}
