package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseHotKeys;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class HotKeys extends BaseHotKeys<HotKeys> {
	public static final HotKeys dao = new HotKeys().dao();
}
