package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseIntegralWalletRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IntegralWalletRecord extends BaseIntegralWalletRecord<IntegralWalletRecord> {
	public static final IntegralWalletRecord dao = new IntegralWalletRecord().dao();
}
