package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseIntegraltype;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Integraltype extends BaseIntegraltype<Integraltype> {
	public static final Integraltype dao = new Integraltype().dao();
}
