package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseIntegral;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Integral extends BaseIntegral<Integral> {
	public static final Integral dao = new Integral().dao();
}
