package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseIntegralLevleInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IntegralLevleInfo extends BaseIntegralLevleInfo<IntegralLevleInfo> {
	public static final IntegralLevleInfo dao = new IntegralLevleInfo().dao();
}
