package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseInterface;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Interface extends BaseInterface<Interface> {
	public static final Interface dao = new Interface().dao();
}
