package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseInviteRegRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class InviteRegRecord extends BaseInviteRegRecord<InviteRegRecord> {
	public static final InviteRegRecord dao = new InviteRegRecord().dao();
}
