package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseInviteMsg;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class InviteMsg extends BaseInviteMsg<InviteMsg> {
	public static final InviteMsg dao = new InviteMsg().dao();
}
