package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseIpTable;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IpTable extends BaseIpTable<IpTable> {
	public static final IpTable dao = new IpTable().dao();
}
