package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseLeftcategory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Leftcategory extends BaseLeftcategory<Leftcategory> {
	public static final Leftcategory dao = new Leftcategory().dao();
}
