package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseLessonReplyComment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LessonReplyComment extends BaseLessonReplyComment<LessonReplyComment> {
	public static final LessonReplyComment dao = new LessonReplyComment().dao();
}
