package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseLessonScriptReplyGroupRel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LessonScriptReplyGroupRel extends BaseLessonScriptReplyGroupRel<LessonScriptReplyGroupRel> {
	public static final LessonScriptReplyGroupRel dao = new LessonScriptReplyGroupRel().dao();
}
