package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseLessonProductOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LessonProductOrder extends BaseLessonProductOrder<LessonProductOrder> {
	public static final LessonProductOrder dao = new LessonProductOrder().dao();
}
