package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseLessonScriptReplyLike;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LessonScriptReplyLike extends BaseLessonScriptReplyLike<LessonScriptReplyLike> {
	public static final LessonScriptReplyLike dao = new LessonScriptReplyLike().dao();
}
