package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseLessonRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LessonRecord extends BaseLessonRecord<LessonRecord> {
	public static final LessonRecord dao = new LessonRecord().dao();
}
