package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseLessonScriptReplyScore;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LessonScriptReplyScore extends BaseLessonScriptReplyScore<LessonScriptReplyScore> {
	public static final LessonScriptReplyScore dao = new LessonScriptReplyScore().dao();
}
