package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseLessonAds;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LessonAds extends BaseLessonAds<LessonAds> {
	public static final LessonAds dao = new LessonAds().dao();
}
