package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseLessonFeedback;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LessonFeedback extends BaseLessonFeedback<LessonFeedback> {
	public static final LessonFeedback dao = new LessonFeedback().dao();
}
