package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseLessonScriptReplyGroup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LessonScriptReplyGroup extends BaseLessonScriptReplyGroup<LessonScriptReplyGroup> {
	public static final LessonScriptReplyGroup dao = new LessonScriptReplyGroup().dao();
}
