package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseLevelLogo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LevelLogo extends BaseLevelLogo<LevelLogo> {
	public static final LevelLogo dao = new LevelLogo().dao();
}
