package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseLevelPicInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LevelPicInfo extends BaseLevelPicInfo<LevelPicInfo> {
	public static final LevelPicInfo dao = new LevelPicInfo().dao();
}
