package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseLibraryProduct;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LibraryProduct extends BaseLibraryProduct<LibraryProduct> {
	public static final LibraryProduct dao = new LibraryProduct().dao();
}
