package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseLifeConvertRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LifeConvertRecord extends BaseLifeConvertRecord<LifeConvertRecord> {
	public static final LifeConvertRecord dao = new LifeConvertRecord().dao();
}
