package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseLiveLesson;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LiveLesson extends BaseLiveLesson<LiveLesson> {
	public static final LiveLesson dao = new LiveLesson().dao();
}
