package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseLiveLessonRel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LiveLessonRel extends BaseLiveLessonRel<LiveLessonRel> {
	public static final LiveLessonRel dao = new LiveLessonRel().dao();
}
