package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseLiveScriptStatus;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LiveScriptStatus extends BaseLiveScriptStatus<LiveScriptStatus> {
	public static final LiveScriptStatus dao = new LiveScriptStatus().dao();
}
