package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseLiveLessonGrade;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LiveLessonGrade extends BaseLiveLessonGrade<LiveLessonGrade> {
	public static final LiveLessonGrade dao = new LiveLessonGrade().dao();
}
