package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseMallProductOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MallProductOrder extends BaseMallProductOrder<MallProductOrder> {
	public static final MallProductOrder dao = new MallProductOrder().dao();
}
