package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseMallbanner;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Mallbanner extends BaseMallbanner<Mallbanner> {
	public static final Mallbanner dao = new Mallbanner().dao();
}
