package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseMallorderservice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Mallorderservice extends BaseMallorderservice<Mallorderservice> {
	public static final Mallorderservice dao = new Mallorderservice().dao();
}
