package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseMallOrderStatus;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MallOrderStatus extends BaseMallOrderStatus<MallOrderStatus> {
	public static final MallOrderStatus dao = new MallOrderStatus().dao();
}
