package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseMallproductCopy;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MallproductCopy extends BaseMallproductCopy<MallproductCopy> {
	public static final MallproductCopy dao = new MallproductCopy().dao();
}
