package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseMallProductCategory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MallProductCategory extends BaseMallProductCategory<MallProductCategory> {
	public static final MallProductCategory dao = new MallProductCategory().dao();
}
