package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseMallProductSpec;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MallProductSpec extends BaseMallProductSpec<MallProductSpec> {
	public static final MallProductSpec dao = new MallProductSpec().dao();
}
