package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseMallproductkeyword;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Mallproductkeyword extends BaseMallproductkeyword<Mallproductkeyword> {
	public static final Mallproductkeyword dao = new Mallproductkeyword().dao();
}
