package com.wechat.jfinal.model;

import java.util.Iterator;
import java.util.List;

import com.jfinal.plugin.activerecord.Page;
import com.wechat.jfinal.model.base.BaseMallproduct;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Mallproduct extends BaseMallproduct<Mallproduct> {
	public static final Mallproduct dao = new Mallproduct().dao();

	public Page<Mallproduct> findByLabel(int label, int pageNumber, int pageSize) {
		return Mallproduct.dao.paginate(pageNumber, pageSize, "select a.*","FROM `productlabel` a,mallproduct b WHERE a.id = ? AND a.productid = b.id ",label);
	}
	
	public Page<Mallproduct> findGradeProductsByLabel(int label, int pageNumber, int pageSize) {
		return Mallproduct.dao.paginate(pageNumber, pageSize, "select a.*","FROM `productlabel` a,mallproduct b WHERE a.id = ? AND a.productid = b.id AND b.class_grade_id > 0",label);
	}
	
	public Page<Mallproduct> findLessonPackByLabel(int label, int pageNumber, int pageSize) {
		return Mallproduct.dao.paginate(pageNumber, pageSize, "select a.*","FROM `productlabel` a,mallproduct b WHERE a.id = ? AND a.productid = b.id AND b.class_room_package > 0",label);
	}
	
	

}
