package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseMallProductRebateCode;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MallProductRebateCode extends BaseMallProductRebateCode<MallProductRebateCode> {
	public static final MallProductRebateCode dao = new MallProductRebateCode().dao();
}
