package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseMallProduct2;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MallProduct2 extends BaseMallProduct2<MallProduct2> {
	public static final MallProduct2 dao = new MallProduct2().dao();
}
