package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseMallorder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Mallorder extends BaseMallorder<Mallorder> {
	public static final Mallorder dao = new Mallorder().dao();
}
