package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseMallorderproduct;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Mallorderproduct extends BaseMallorderproduct<Mallorderproduct> {
	public static final Mallorderproduct dao = new Mallorderproduct().dao();
}
