package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseMallspecifications;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Mallspecifications extends BaseMallspecifications<Mallspecifications> {
	public static final Mallspecifications dao = new Mallspecifications().dao();
}
