package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseMaterialFile;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MaterialFile extends BaseMaterialFile<MaterialFile> {
	public static final MaterialFile dao = new MaterialFile().dao();
}
