package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseMaterialPath;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MaterialPath extends BaseMaterialPath<MaterialPath> {
	public static final MaterialPath dao = new MaterialPath().dao();
}
