package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseMediainfoWords;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MediainfoWords extends BaseMediainfoWords<MediainfoWords> {
	public static final MediainfoWords dao = new MediainfoWords().dao();
}
