package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseMemberpayment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Memberpayment extends BaseMemberpayment<Memberpayment> {
	public static final Memberpayment dao = new Memberpayment().dao();
}
