package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseMemberaccount;
import com.wechat.util.MD5UTIL;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Memberaccount extends BaseMemberaccount<Memberaccount> {

	private final String defaultPassWord = "123456";

	public static final Memberaccount dao = new Memberaccount().dao();

	public boolean isDefaultPwd(){
		return getPassword().equalsIgnoreCase(MD5UTIL.encrypt(defaultPassWord));
	}
	
	public boolean isDefaultPwd(String password){
		return password.equalsIgnoreCase(MD5UTIL.encrypt(defaultPassWord));
	}
	
}
