package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseMemberbook;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Memberbook extends BaseMemberbook<Memberbook> {
	public static final Memberbook dao = new Memberbook().dao();
}
