package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseMembergame;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Membergame extends BaseMembergame<Membergame> {
	public static final Membergame dao = new Membergame().dao();
}
