package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseMembercollection;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Membercollection extends BaseMembercollection<Membercollection> {
	public static final Membercollection dao = new Membercollection().dao();
}
