package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseMemBook;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MemBook extends BaseMemBook<MemBook> {
	public static final MemBook dao = new MemBook().dao();
}
