package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseMemberbookinfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Memberbookinfo extends BaseMemberbookinfo<Memberbookinfo> {
	public static final Memberbookinfo dao = new Memberbookinfo().dao();
}
