package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseMemberUserAgent;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MemberUserAgent extends BaseMemberUserAgent<MemberUserAgent> {
	public static final MemberUserAgent dao = new MemberUserAgent().dao();
}
