package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseMembermp3;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Membermp3 extends BaseMembermp3<Membermp3> {
	public static final Membermp3 dao = new Membermp3().dao();
}
