package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseMember;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Member extends BaseMember<Member> {
	public static final Member dao = new Member().dao();
}
