package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseMember1;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Member1 extends BaseMember1<Member1> {
	public static final Member1 dao = new Member1().dao();
}
