package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseMyliber;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Myliber extends BaseMyliber<Myliber> {
	public static final Myliber dao = new Myliber().dao();
}
