package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseOnlineClassDeleteStudentRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OnlineClassDeleteStudentRecord extends BaseOnlineClassDeleteStudentRecord<OnlineClassDeleteStudentRecord> {
	public static final OnlineClassDeleteStudentRecord dao = new OnlineClassDeleteStudentRecord().dao();
}
