package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseOnlineClassComment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OnlineClassComment extends BaseOnlineClassComment<OnlineClassComment> {
	public static final OnlineClassComment dao = new OnlineClassComment().dao();
}
