package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseOrderStudentRoompack;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderStudentRoompack extends BaseOrderStudentRoompack<OrderStudentRoompack> {
	public static final OrderStudentRoompack dao = new OrderStudentRoompack().dao();
}
