package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseOrderstatus;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Orderstatus extends BaseOrderstatus<Orderstatus> {
	public static final Orderstatus dao = new Orderstatus().dao();
}
