package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseOssUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OssUser extends BaseOssUser<OssUser> {
	public static final OssUser dao = new OssUser().dao();
}
