package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BasePcManageRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PcManageRole extends BasePcManageRole<PcManageRole> {
	public static final PcManageRole dao = new PcManageRole().dao();
}
