package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BasePcManageMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PcManageMenu extends BasePcManageMenu<PcManageMenu> {
	public static final PcManageMenu dao = new PcManageMenu().dao();
}
