package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BasePcManageMenuRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PcManageMenuRole extends BasePcManageMenuRole<PcManageMenuRole> {
	public static final PcManageMenuRole dao = new PcManageMenuRole().dao();
}
