package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BasePopularize;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Popularize extends BasePopularize<Popularize> {
	public static final Popularize dao = new Popularize().dao();
}
