package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseProductlabel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Productlabel extends BaseProductlabel<Productlabel> {
	public static final Productlabel dao = new Productlabel().dao();
}
