package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseProductCategoryShow;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProductCategoryShow extends BaseProductCategoryShow<ProductCategoryShow> {
	public static final ProductCategoryShow dao = new ProductCategoryShow().dao();
}
