package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseProvince;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Province extends BaseProvince<Province> {
	public static final Province dao = new Province().dao();
}
