package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BasePurchaseMemberTrade;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PurchaseMemberTrade extends BasePurchaseMemberTrade<PurchaseMemberTrade> {
	public static final PurchaseMemberTrade dao = new PurchaseMemberTrade().dao();
}
