package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BasePushHistory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PushHistory extends BasePushHistory<PushHistory> {
	public static final PushHistory dao = new PushHistory().dao();
}
