package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseQiniuFileLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QiniuFileLog extends BaseQiniuFileLog<QiniuFileLog> {
	public static final QiniuFileLog dao = new QiniuFileLog().dao();
}
