package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseQuestion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Question extends BaseQuestion<Question> {
	public static final Question dao = new Question().dao();
}
