package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseQyAppAccout;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QyAppAccout extends BaseQyAppAccout<QyAppAccout> {
	public static final QyAppAccout dao = new QyAppAccout().dao();
}
