package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseQyAppMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QyAppMenu extends BaseQyAppMenu<QyAppMenu> {
	public static final QyAppMenu dao = new QyAppMenu().dao();
}
