package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseQyAppRoleMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QyAppRoleMenu extends BaseQyAppRoleMenu<QyAppRoleMenu> {
	public static final QyAppRoleMenu dao = new QyAppRoleMenu().dao();
}
