package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseQyAppRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QyAppRole extends BaseQyAppRole<QyAppRole> {
	public static final QyAppRole dao = new QyAppRole().dao();
}
