package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseQyClass;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QyClass extends BaseQyClass<QyClass> {
	public static final QyClass dao = new QyClass().dao();
}
