package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseQyDevice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QyDevice extends BaseQyDevice<QyDevice> {
	public static final QyDevice dao = new QyDevice().dao();
}
