package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseQyPunchActionRule;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QyPunchActionRule extends BaseQyPunchActionRule<QyPunchActionRule> {
	public static final QyPunchActionRule dao = new QyPunchActionRule().dao();
}
