package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseQyPunchActionType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QyPunchActionType extends BaseQyPunchActionType<QyPunchActionType> {
	public static final QyPunchActionType dao = new QyPunchActionType().dao();
}
