package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseQyStudent;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QyStudent extends BaseQyStudent<QyStudent> {
	public static final QyStudent dao = new QyStudent().dao();
}
