package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseQyStudentToCard;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QyStudentToCard extends BaseQyStudentToCard<QyStudentToCard> {
	public static final QyStudentToCard dao = new QyStudentToCard().dao();
}
