package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseQyUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QyUser extends BaseQyUser<QyUser> {
	public static final QyUser dao = new QyUser().dao();
}
