package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseReadbookrecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Readbookrecord extends BaseReadbookrecord<Readbookrecord> {
	public static final Readbookrecord dao = new Readbookrecord().dao();
}
