package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseRecommend;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Recommend extends BaseRecommend<Recommend> {
	public static final Recommend dao = new Recommend().dao();
}
