package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseReplies;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Replies extends BaseReplies<Replies> {
	public static final Replies dao = new Replies().dao();
}
