package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseReplacement;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Replacement extends BaseReplacement<Replacement> {
	public static final Replacement dao = new Replacement().dao();
}
