package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseResourceFolderRel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ResourceFolderRel extends BaseResourceFolderRel<ResourceFolderRel> {
	public static final ResourceFolderRel dao = new ResourceFolderRel().dao();
}
