package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseRfid;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Rfid extends BaseRfid<Rfid> {
	public static final Rfid dao = new Rfid().dao();
}
