package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseRfidAssociate;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RfidAssociate extends BaseRfidAssociate<RfidAssociate> {
	public static final RfidAssociate dao = new RfidAssociate().dao();

    public List<RfidAssociate> findByAccount(String account) {
        return find("SELECT ra.* FROM rfid_associate ra,memberaccount mac WHERE mac.account = ? AND mac.id = ra.account_id AND ra.`status` = 1",account);
    }

    public static void main(String[] args) {
        StringBuffer studentSql = new StringBuffer(
                "SELECT a.sex,date_format(a.birthday, '%Y-%m-%d') as birthday,a.id,a.`name`,ifnull(a.epal_id,'') as epal_id,a.create_time,a.student_type,a.sort_id,");
        studentSql
                .append("IFNULL(a.integral,0) AS integral ,IFNULL(a.contribution,0) AS contribution,a.remark,");
        studentSql.append(
                "a.member_id,a.degree_of_difficulty,a.avatar,a.`status`,c.epal_pwd,ifnull(c.device_type,'') as device_type,c.nickname,a.lesson_integral FROM class_student");
        studentSql.append(
                " a,device_relation b,device c WHERE a.epal_id = b.epal_id AND b.epal_id = c.epal_id AND b.friend_id ");
        studentSql.append(
                "= ? and b.isbind = 1 and a.status > -1 UNION SELECT a.sex,date_format(a.birthday, '%Y-%m-%d') as birthday,a.id,a.`name`,ifnull(a.epal_id,'') as epal_id,a.create_time,a.student_type,a.");
        studentSql.append(
                "sort_id,IFNULL(a.integral,0) AS integral ,IFNULL(a.contribution,0) AS contribution,a.remark,a.member_id,");
        studentSql.append(
                "a.degree_of_difficulty,a.avatar,a.`status`,b.epal_pwd,ifnull(b.device_type,'') as device_type,b.nickname,a.lesson_integral FROM `class_student` a,device b WHERE ");
        studentSql.append("a.epal_id = b.epal_id AND a.member_id = ? and a.status > -1");

        System.out.println("studentSql = " + studentSql);
    }

    public List<RfidAssociate> findByStudent(int studentId) {

        return find("SELECT * FROM `rfid_associate` WHERE student_id = ? and `status` = 1 ",studentId );
    }
}
