package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseRobotHourse;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RobotHourse extends BaseRobotHourse<RobotHourse> {
	public static final RobotHourse dao = new RobotHourse().dao();
}
