package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseRobotState;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RobotState extends BaseRobotState<RobotState> {
	public static final RobotState dao = new RobotState().dao();
}
