package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseRolemodular;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Rolemodular extends BaseRolemodular<Rolemodular> {
	public static final Rolemodular dao = new Rolemodular().dao();
}
