package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseRoomPackage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RoomPackage extends BaseRoomPackage<RoomPackage> {
	public static final RoomPackage dao = new RoomPackage().dao();
}
