package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseSchoolClass;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SchoolClass extends BaseSchoolClass<SchoolClass> {
	public static final SchoolClass dao = new SchoolClass().dao();
}
