package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseShareGetLesson;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ShareGetLesson extends BaseShareGetLesson<ShareGetLesson> {
	public static final ShareGetLesson dao = new ShareGetLesson().dao();
}
