package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseShoporder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Shoporder extends BaseShoporder<Shoporder> {
	public static final Shoporder dao = new Shoporder().dao();
}
