package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseSmscode;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Smscode extends BaseSmscode<Smscode> {
	public static final Smscode dao = new Smscode().dao();
}
