package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseSnpMallBanner;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SnpMallBanner extends BaseSnpMallBanner<SnpMallBanner> {
	public static final SnpMallBanner dao = new SnpMallBanner().dao();
}
