package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseSoundTagSource;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SoundTagSource extends BaseSoundTagSource<SoundTagSource> {
	public static final SoundTagSource dao = new SoundTagSource().dao();
}
