package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseSoundRecommendGroupToSound;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SoundRecommendGroupToSound extends BaseSoundRecommendGroupToSound<SoundRecommendGroupToSound> {
	public static final SoundRecommendGroupToSound dao = new SoundRecommendGroupToSound().dao();
}
