package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseSoundRecommendGroup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SoundRecommendGroup extends BaseSoundRecommendGroup<SoundRecommendGroup> {
	public static final SoundRecommendGroup dao = new SoundRecommendGroup().dao();
}
