package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseSoundBest;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SoundBest extends BaseSoundBest<SoundBest> {
	public static final SoundBest dao = new SoundBest().dao();
}
