package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseSpecial;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Special extends BaseSpecial<Special> {
	public static final Special dao = new Special().dao();
}
