package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseSpecialinfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Specialinfo extends BaseSpecialinfo<Specialinfo> {
	public static final Specialinfo dao = new Specialinfo().dao();
}
