package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseStdDiyStudyDay;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StdDiyStudyDay extends BaseStdDiyStudyDay<StdDiyStudyDay> {
	public static final StdDiyStudyDay dao = new StdDiyStudyDay().dao();
}
