package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseStdToAgent;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StdToAgent extends BaseStdToAgent<StdToAgent> {
	public static final StdToAgent dao = new StdToAgent().dao();
}
