package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseStroeProduct;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StroeProduct extends BaseStroeProduct<StroeProduct> {
	public static final StroeProduct dao = new StroeProduct().dao();
}
