package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseStudyCoinCard;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StudyCoinCard extends BaseStudyCoinCard<StudyCoinCard> {
	public static final StudyCoinCard dao = new StudyCoinCard().dao();
}
