package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseStudyCoinCardCategory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StudyCoinCardCategory extends BaseStudyCoinCardCategory<StudyCoinCardCategory> {
	public static final StudyCoinCardCategory dao = new StudyCoinCardCategory().dao();
}
