package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseStudyPhoto;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StudyPhoto extends BaseStudyPhoto<StudyPhoto> {
	public static final StudyPhoto dao = new StudyPhoto().dao();
}
