package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseTable;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Table extends BaseTable<Table> {
	public static final Table dao = new Table().dao();
}
