package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseTeacherCollectionClassRoom;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TeacherCollectionClassRoom extends BaseTeacherCollectionClassRoom<TeacherCollectionClassRoom> {
	public static final TeacherCollectionClassRoom dao = new TeacherCollectionClassRoom().dao();
}
