package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseTemporaryLoginCode;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TemporaryLoginCode extends BaseTemporaryLoginCode<TemporaryLoginCode> {
	public static final TemporaryLoginCode dao = new TemporaryLoginCode().dao();
}
