package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseTrainQuestionItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TrainQuestionItem extends BaseTrainQuestionItem<TrainQuestionItem> {
	public static final TrainQuestionItem dao = new TrainQuestionItem().dao();
}
