package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseTrainAnswerItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TrainAnswerItem extends BaseTrainAnswerItem<TrainAnswerItem> {
	public static final TrainAnswerItem dao = new TrainAnswerItem().dao();
}
