package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseTrainKnowledge;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TrainKnowledge extends BaseTrainKnowledge<TrainKnowledge> {
	public static final TrainKnowledge dao = new TrainKnowledge().dao();
}
