package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseTransactionRecords;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TransactionRecords extends BaseTransactionRecords<TransactionRecords> {
	public static final TransactionRecords dao = new TransactionRecords().dao();
}
