package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseTrialUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TrialUser extends BaseTrialUser<TrialUser> {
	public static final TrialUser dao = new TrialUser().dao();
}
