package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseTSchool;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TSchool extends BaseTSchool<TSchool> {
	public static final TSchool dao = new TSchool().dao();
}
