package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseUserToClassGrades;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserToClassGrades extends BaseUserToClassGrades<UserToClassGrades> {
	public static final UserToClassGrades dao = new UserToClassGrades().dao();
}
