package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseUserAnswerHistory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserAnswerHistory extends BaseUserAnswerHistory<UserAnswerHistory> {
	public static final UserAnswerHistory dao = new UserAnswerHistory().dao();
}
