package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseUserChannel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserChannel extends BaseUserChannel<UserChannel> {
	public static final UserChannel dao = new UserChannel().dao();
}
