package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseUserSign;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserSign extends BaseUserSign<UserSign> {
	public static final UserSign dao = new UserSign().dao();
}
