package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseUseraddress;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Useraddress extends BaseUseraddress<Useraddress> {
	public static final Useraddress dao = new Useraddress().dao();
}
