package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseVideoVote;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VideoVote extends BaseVideoVote<VideoVote> {
	public static final VideoVote dao = new VideoVote().dao();
}
