package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseVideoLikeRecoad;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VideoLikeRecoad extends BaseVideoLikeRecoad<VideoLikeRecoad> {
	public static final VideoLikeRecoad dao = new VideoLikeRecoad().dao();
}
