package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseVideoScore;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VideoScore extends BaseVideoScore<VideoScore> {
	public static final VideoScore dao = new VideoScore().dao();
}
