package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseVideoAccess;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VideoAccess extends BaseVideoAccess<VideoAccess> {
	public static final VideoAccess dao = new VideoAccess().dao();
}
