package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseVideoInviteMessage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VideoInviteMessage extends BaseVideoInviteMessage<VideoInviteMessage> {
	public static final VideoInviteMessage dao = new VideoInviteMessage().dao();
}
