package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseVideoCollection;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VideoCollection extends BaseVideoCollection<VideoCollection> {
	public static final VideoCollection dao = new VideoCollection().dao();
}
