package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseVideoMemberVoteCount;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VideoMemberVoteCount extends BaseVideoMemberVoteCount<VideoMemberVoteCount> {
	public static final VideoMemberVoteCount dao = new VideoMemberVoteCount().dao();
}
