package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseWallet;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Wallet extends BaseWallet<Wallet> {
	public static final Wallet dao = new Wallet().dao();
}
