package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseWechatUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WechatUser extends BaseWechatUser<WechatUser> {
	public static final WechatUser dao = new WechatUser().dao();
}
