package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseWellLesson;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WellLesson extends BaseWellLesson<WellLesson> {
	public static final WellLesson dao = new WellLesson().dao();
}
