package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseWorksEval;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WorksEval extends BaseWorksEval<WorksEval> {
	public static final WorksEval dao = new WorksEval().dao();
}
