package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseXmlyChannelAlbum;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class XmlyChannelAlbum extends BaseXmlyChannelAlbum<XmlyChannelAlbum> {
	public static final XmlyChannelAlbum dao = new XmlyChannelAlbum().dao();
}
