package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseXmlyChannel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class XmlyChannel extends BaseXmlyChannel<XmlyChannel> {
	public static final XmlyChannel dao = new XmlyChannel().dao();
}
