package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseXmlyAlbum;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class XmlyAlbum extends BaseXmlyAlbum<XmlyAlbum> {
	public static final XmlyAlbum dao = new XmlyAlbum().dao();
}
