package com.wechat.jfinal.model;

import com.wechat.jfinal.model.base.BaseZhuboAlias;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZhuboAlias extends BaseZhuboAlias<ZhuboAlias> {
	public static final ZhuboAlias dao = new ZhuboAlias().dao();
}
