package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseClassSlot<M extends BaseClassSlot<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return getStr("name");
	}

	public M setEpalId(java.lang.String epalId) {
		set("epal_id", epalId);
		return (M)this;
	}

	public java.lang.String getEpalId() {
		return getStr("epal_id");
	}

	public M setDoTime(java.lang.String doTime) {
		set("do_time", doTime);
		return (M)this;
	}

	public java.lang.String getDoTime() {
		return getStr("do_time");
	}

	public M setDoSlot(java.lang.Integer doSlot) {
		set("do_slot", doSlot);
		return (M)this;
	}

	public java.lang.Integer getDoSlot() {
		return getInt("do_slot");
	}

}
