package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseIntegralWalletRecord<M extends BaseIntegralWalletRecord<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setIntegralWalletId(java.lang.Integer integralWalletId) {
		set("integral_wallet_id", integralWalletId);
		return (M)this;
	}

	public java.lang.Integer getIntegralWalletId() {
		return getInt("integral_wallet_id");
	}

	public M setDetail(java.lang.Integer detail) {
		set("detail", detail);
		return (M)this;
	}

	public java.lang.Integer getDetail() {
		return getInt("detail");
	}

	public M setDescription(java.lang.String description) {
		set("description", description);
		return (M)this;
	}

	public java.lang.String getDescription() {
		return getStr("description");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
