package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMaterialPathFileRel<M extends BaseMaterialPathFileRel<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setMaterialFileId(java.lang.Integer materialFileId) {
		set("material_file_id", materialFileId);
		return (M)this;
	}

	public java.lang.Integer getMaterialFileId() {
		return getInt("material_file_id");
	}

	public M setMaterialPathId(java.lang.Integer materialPathId) {
		set("material_path_id", materialPathId);
		return (M)this;
	}

	public java.lang.Integer getMaterialPathId() {
		return getInt("material_path_id");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
