package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCachfolder<M extends BaseCachfolder<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setCatalog(java.lang.String catalog) {
		set("catalog", catalog);
		return (M)this;
	}

	public java.lang.String getCatalog() {
		return getStr("catalog");
	}

	public M setPosition(java.lang.Long position) {
		set("position", position);
		return (M)this;
	}

	public java.lang.Long getPosition() {
		return getLong("position");
	}

	public M setEpalid(java.lang.String epalid) {
		set("epalid", epalid);
		return (M)this;
	}

	public java.lang.String getEpalid() {
		return getStr("epalid");
	}

	public M setLastid(java.lang.Long lastid) {
		set("lastid", lastid);
		return (M)this;
	}

	public java.lang.Long getLastid() {
		return getLong("lastid");
	}

}
