package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseComment1<M extends BaseComment1<M>> extends Model<M> implements IBean {

	public M setCid(java.lang.Integer cid) {
		set("cid", cid);
		return (M)this;
	}

	public java.lang.Integer getCid() {
		return getInt("cid");
	}

	public M setContent(java.lang.String content) {
		set("content", content);
		return (M)this;
	}

	public java.lang.String getContent() {
		return getStr("content");
	}

	public M setImgpath(java.lang.String imgpath) {
		set("imgpath", imgpath);
		return (M)this;
	}

	public java.lang.String getImgpath() {
		return getStr("imgpath");
	}

	public M setMemId(java.lang.String memId) {
		set("mem_id", memId);
		return (M)this;
	}

	public java.lang.String getMemId() {
		return getStr("mem_id");
	}

	public M setCateId(java.lang.String cateId) {
		set("cate_id", cateId);
		return (M)this;
	}

	public java.lang.String getCateId() {
		return getStr("cate_id");
	}

}
