package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseEovaUser<M extends BaseEovaUser<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setLoginId(java.lang.String loginId) {
		set("login_id", loginId);
		return (M)this;
	}

	public java.lang.String getLoginId() {
		return getStr("login_id");
	}

	public M setLoginPwd(java.lang.String loginPwd) {
		set("login_pwd", loginPwd);
		return (M)this;
	}

	public java.lang.String getLoginPwd() {
		return getStr("login_pwd");
	}

	public M setRid(java.lang.Integer rid) {
		set("rid", rid);
		return (M)this;
	}

	public java.lang.Integer getRid() {
		return getInt("rid");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return getStr("name");
	}

	public M setMemo(java.lang.String memo) {
		set("memo", memo);
		return (M)this;
	}

	public java.lang.String getMemo() {
		return getStr("memo");
	}

	public M setAgentId(java.lang.Integer agentId) {
		set("agent_id", agentId);
		return (M)this;
	}

	public java.lang.Integer getAgentId() {
		return getInt("agent_id");
	}

}
