package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseClassRoomStatistics<M extends BaseClassRoomStatistics<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setClassRoomId(java.lang.Integer classRoomId) {
		set("class_room_id", classRoomId);
		return (M)this;
	}

	public java.lang.Integer getClassRoomId() {
		return getInt("class_room_id");
	}

	public M setClassNumber(java.lang.Integer classNumber) {
		set("class_number", classNumber);
		return (M)this;
	}

	public java.lang.Integer getClassNumber() {
		return getInt("class_number");
	}

	public M setAttendanceNumber(java.lang.Integer attendanceNumber) {
		set("attendance_number", attendanceNumber);
		return (M)this;
	}

	public java.lang.Integer getAttendanceNumber() {
		return getInt("attendance_number");
	}

	public M setCompleteNumber(java.lang.Integer completeNumber) {
		set("complete_number", completeNumber);
		return (M)this;
	}

	public java.lang.Integer getCompleteNumber() {
		return getInt("complete_number");
	}

	public M setUpdateTime(java.lang.String updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}

	public java.lang.String getUpdateTime() {
		return getStr("update_time");
	}

	public M setClassRoomName(java.lang.String classRoomName) {
		set("classRoomName", classRoomName);
		return (M)this;
	}

	public java.lang.String getClassRoomName() {
		return getStr("classRoomName");
	}

	public M setTeacherName(java.lang.String teacherName) {
		set("teacherName", teacherName);
		return (M)this;
	}

	public java.lang.String getTeacherName() {
		return getStr("teacherName");
	}

}
