package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMallorderproduct<M extends BaseMallorderproduct<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setOrderid(java.lang.Integer orderid) {
		set("orderid", orderid);
		return (M)this;
	}

	public java.lang.Integer getOrderid() {
		return getInt("orderid");
	}

	public M setProductid(java.lang.Integer productid) {
		set("productid", productid);
		return (M)this;
	}

	public java.lang.Integer getProductid() {
		return getInt("productid");
	}

	public M setCreatedate(java.util.Date createdate) {
		set("createdate", createdate);
		return (M)this;
	}

	public java.util.Date getCreatedate() {
		return get("createdate");
	}

	public M setSpecifications(java.lang.String specifications) {
		set("specifications", specifications);
		return (M)this;
	}

	public java.lang.String getSpecifications() {
		return getStr("specifications");
	}

	public M setProductName(java.lang.String productName) {
		set("productName", productName);
		return (M)this;
	}

	public java.lang.String getProductName() {
		return getStr("productName");
	}

	public M setProductImg(java.lang.String productImg) {
		set("productImg", productImg);
		return (M)this;
	}

	public java.lang.String getProductImg() {
		return getStr("productImg");
	}

	public M setPrice(java.lang.Double price) {
		set("price", price);
		return (M)this;
	}

	public java.lang.Double getPrice() {
		return getDouble("price");
	}

	public M setCount(java.lang.Integer count) {
		set("count", count);
		return (M)this;
	}

	public java.lang.Integer getCount() {
		return getInt("count");
	}

	public M setCommentstatus(java.lang.Integer commentstatus) {
		set("commentstatus", commentstatus);
		return (M)this;
	}

	public java.lang.Integer getCommentstatus() {
		return getInt("commentstatus");
	}

}
