package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseIpTable<M extends BaseIpTable<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setIP(java.lang.String IP) {
		set("IP", IP);
		return (M)this;
	}

	public java.lang.String getIP() {
		return getStr("IP");
	}

	public M setProvince(java.lang.String province) {
		set("province", province);
		return (M)this;
	}

	public java.lang.String getProvince() {
		return getStr("province");
	}

	public M setCity(java.lang.String city) {
		set("city", city);
		return (M)this;
	}

	public java.lang.String getCity() {
		return getStr("city");
	}

	public M setOperator(java.lang.String operator) {
		set("operator", operator);
		return (M)this;
	}

	public java.lang.String getOperator() {
		return getStr("operator");
	}

	public M setInsertTime(java.lang.String insertTime) {
		set("insert_time", insertTime);
		return (M)this;
	}

	public java.lang.String getInsertTime() {
		return getStr("insert_time");
	}

	public M setCountry(java.lang.String country) {
		set("country", country);
		return (M)this;
	}

	public java.lang.String getCountry() {
		return getStr("country");
	}

	public M setArea(java.lang.String area) {
		set("area", area);
		return (M)this;
	}

	public java.lang.String getArea() {
		return getStr("area");
	}

}
