package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAnswer<M extends BaseAnswer<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setAnswer(java.lang.String answer) {
		set("answer", answer);
		return (M)this;
	}

	public java.lang.String getAnswer() {
		return getStr("answer");
	}

	public M setInsertDate(java.util.Date insertDate) {
		set("insert_date", insertDate);
		return (M)this;
	}

	public java.util.Date getInsertDate() {
		return get("insert_date");
	}

	public M setQuestionId(java.lang.Integer questionId) {
		set("question_id", questionId);
		return (M)this;
	}

	public java.lang.Integer getQuestionId() {
		return getInt("question_id");
	}

}
