package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMiniappMember<M extends BaseMiniappMember<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setNickName(java.lang.String nickName) {
		set("nick_name", nickName);
		return (M)this;
	}

	public java.lang.String getNickName() {
		return getStr("nick_name");
	}

	public M setAvatarUrl(java.lang.String avatarUrl) {
		set("avatar_url", avatarUrl);
		return (M)this;
	}

	public java.lang.String getAvatarUrl() {
		return getStr("avatar_url");
	}

	public M setGender(java.lang.Integer gender) {
		set("gender", gender);
		return (M)this;
	}

	public java.lang.Integer getGender() {
		return getInt("gender");
	}

	public M setMiniappOpenid(java.lang.String miniappOpenid) {
		set("miniapp_openid", miniappOpenid);
		return (M)this;
	}

	public java.lang.String getMiniappOpenid() {
		return getStr("miniapp_openid");
	}

	public M setMobile(java.lang.String mobile) {
		set("mobile", mobile);
		return (M)this;
	}

	public java.lang.String getMobile() {
		return getStr("mobile");
	}

	public M setCountry(java.lang.String country) {
		set("country", country);
		return (M)this;
	}

	public java.lang.String getCountry() {
		return getStr("country");
	}

	public M setProvince(java.lang.String province) {
		set("province", province);
		return (M)this;
	}

	public java.lang.String getProvince() {
		return getStr("province");
	}

	public M setCity(java.lang.String city) {
		set("city", city);
		return (M)this;
	}

	public java.lang.String getCity() {
		return getStr("city");
	}

	public M setLanguage(java.lang.String language) {
		set("language", language);
		return (M)this;
	}

	public java.lang.String getLanguage() {
		return getStr("language");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public M setLastLogin(java.util.Date lastLogin) {
		set("last_login", lastLogin);
		return (M)this;
	}

	public java.util.Date getLastLogin() {
		return get("last_login");
	}

}
