package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseClassCourseCopy1<M extends BaseClassCourseCopy1<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setDoTitle(java.lang.String doTitle) {
		set("do_title", doTitle);
		return (M)this;
	}

	public java.lang.String getDoTitle() {
		return getStr("do_title");
	}

	public M setDoSlot(java.lang.Integer doSlot) {
		set("do_slot", doSlot);
		return (M)this;
	}

	public java.lang.Integer getDoSlot() {
		return getInt("do_slot");
	}

	public M setDoDay(java.lang.Integer doDay) {
		set("do_day", doDay);
		return (M)this;
	}

	public java.lang.Integer getDoDay() {
		return getInt("do_day");
	}

	public M setClassRoomId(java.lang.Integer classRoomId) {
		set("class_room_id", classRoomId);
		return (M)this;
	}

	public java.lang.Integer getClassRoomId() {
		return getInt("class_room_id");
	}

	public M setClassGradesId(java.lang.Integer classGradesId) {
		set("class_grades_id", classGradesId);
		return (M)this;
	}

	public java.lang.Integer getClassGradesId() {
		return getInt("class_grades_id");
	}

	public M setCover(java.lang.String cover) {
		set("cover", cover);
		return (M)this;
	}

	public java.lang.String getCover() {
		return getStr("cover");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setDoDate(java.lang.String doDate) {
		set("do_date", doDate);
		return (M)this;
	}

	public java.lang.String getDoDate() {
		return getStr("do_date");
	}

}
