package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBookorder<M extends BaseBookorder<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setOrdernumber(java.lang.String ordernumber) {
		set("ordernumber", ordernumber);
		return (M)this;
	}

	public java.lang.String getOrdernumber() {
		return getStr("ordernumber");
	}

	public M setMemberid(java.lang.Integer memberid) {
		set("memberid", memberid);
		return (M)this;
	}

	public java.lang.Integer getMemberid() {
		return getInt("memberid");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public M setCreatedate(java.util.Date createdate) {
		set("createdate", createdate);
		return (M)this;
	}

	public java.util.Date getCreatedate() {
		return get("createdate");
	}

	public M setTotalprice(java.lang.Double totalprice) {
		set("totalprice", totalprice);
		return (M)this;
	}

	public java.lang.Double getTotalprice() {
		return getDouble("totalprice");
	}

	public M setFreight(java.lang.Double freight) {
		set("freight", freight);
		return (M)this;
	}

	public java.lang.Double getFreight() {
		return getDouble("freight");
	}

	public M setRemarks(java.lang.String remarks) {
		set("remarks", remarks);
		return (M)this;
	}

	public java.lang.String getRemarks() {
		return getStr("remarks");
	}

	public M setExpress(java.lang.String express) {
		set("express", express);
		return (M)this;
	}

	public java.lang.String getExpress() {
		return getStr("express");
	}

	public M setExpressnumber(java.lang.String expressnumber) {
		set("expressnumber", expressnumber);
		return (M)this;
	}

	public java.lang.String getExpressnumber() {
		return getStr("expressnumber");
	}

	public M setOperatorid(java.lang.Integer operatorid) {
		set("operatorid", operatorid);
		return (M)this;
	}

	public java.lang.Integer getOperatorid() {
		return getInt("operatorid");
	}

	public M setAddressid(java.lang.Integer addressid) {
		set("addressid", addressid);
		return (M)this;
	}

	public java.lang.Integer getAddressid() {
		return getInt("addressid");
	}

	public M setDeposit(java.lang.Double deposit) {
		set("deposit", deposit);
		return (M)this;
	}

	public java.lang.Double getDeposit() {
		return getDouble("deposit");
	}

	public M setIntegral(java.lang.Integer integral) {
		set("integral", integral);
		return (M)this;
	}

	public java.lang.Integer getIntegral() {
		return getInt("integral");
	}

	public M setBookprice(java.lang.Integer bookprice) {
		set("bookprice", bookprice);
		return (M)this;
	}

	public java.lang.Integer getBookprice() {
		return getInt("bookprice");
	}

}
