package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseClassroomPackageRel<M extends BaseClassroomPackageRel<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setPackageId(java.lang.Integer packageId) {
		set("package_id", packageId);
		return (M)this;
	}

	public java.lang.Integer getPackageId() {
		return getInt("package_id");
	}

	public M setClassroomId(java.lang.Integer classroomId) {
		set("classroom_id", classroomId);
		return (M)this;
	}

	public java.lang.Integer getClassroomId() {
		return getInt("classroom_id");
	}

	public M setIsFree(java.lang.Integer isFree) {
		set("is_free", isFree);
		return (M)this;
	}

	public java.lang.Integer getIsFree() {
		return getInt("is_free");
	}

	public M setDoSlot(java.lang.Integer doSlot) {
		set("do_slot", doSlot);
		return (M)this;
	}

	public java.lang.Integer getDoSlot() {
		return getInt("do_slot");
	}

	public M setDoDay(java.lang.Integer doDay) {
		set("do_day", doDay);
		return (M)this;
	}

	public java.lang.Integer getDoDay() {
		return getInt("do_day");
	}

	public M setCredit(java.lang.Integer credit) {
		set("credit", credit);
		return (M)this;
	}

	public java.lang.Integer getCredit() {
		return getInt("credit");
	}

	public M setVersion(java.lang.String version) {
		set("version", version);
		return (M)this;
	}

	public java.lang.String getVersion() {
		return getStr("version");
	}

}
