package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMallProduct2<M extends BaseMallProduct2<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return getStr("name");
	}

	public M setDesc(java.lang.String desc) {
		set("desc", desc);
		return (M)this;
	}

	public java.lang.String getDesc() {
		return getStr("desc");
	}

	public M setPics(java.lang.String pics) {
		set("pics", pics);
		return (M)this;
	}

	public java.lang.String getPics() {
		return getStr("pics");
	}

	public M setVideo(java.lang.String video) {
		set("video", video);
		return (M)this;
	}

	public java.lang.String getVideo() {
		return getStr("video");
	}

	public M setContent(java.lang.String content) {
		set("content", content);
		return (M)this;
	}

	public java.lang.String getContent() {
		return getStr("content");
	}

	public M setPriceRange(java.lang.String priceRange) {
		set("price_range", priceRange);
		return (M)this;
	}

	public java.lang.String getPriceRange() {
		return getStr("price_range");
	}

	public M setBShow(java.lang.Integer bShow) {
		set("b_show", bShow);
		return (M)this;
	}

	public java.lang.Integer getBShow() {
		return getInt("b_show");
	}

	public M setClassRoomPackageId(java.lang.Integer classRoomPackageId) {
		set("class_room_package_id", classRoomPackageId);
		return (M)this;
	}

	public java.lang.Integer getClassRoomPackageId() {
		return getInt("class_room_package_id");
	}

	public M setClassGradeId(java.lang.Integer classGradeId) {
		set("class_grade_id", classGradeId);
		return (M)this;
	}

	public java.lang.Integer getClassGradeId() {
		return getInt("class_grade_id");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
