package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBookShopCategory<M extends BaseBookShopCategory<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setShopid(java.lang.Integer shopid) {
		set("shopid", shopid);
		return (M)this;
	}

	public java.lang.Integer getShopid() {
		return getInt("shopid");
	}

	public M setCategoryid(java.lang.String categoryid) {
		set("categoryid", categoryid);
		return (M)this;
	}

	public java.lang.String getCategoryid() {
		return getStr("categoryid");
	}

}
