package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDailyRecommendSource<M extends BaseDailyRecommendSource<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setSourceId(java.lang.Integer sourceId) {
		set("sourceId", sourceId);
		return (M)this;
	}

	public java.lang.Integer getSourceId() {
		return getInt("sourceId");
	}

	public M setTagId(java.lang.Integer tagId) {
		set("tagId", tagId);
		return (M)this;
	}

	public java.lang.Integer getTagId() {
		return getInt("tagId");
	}

	public M setSortId(java.lang.Integer sortId) {
		set("sortId", sortId);
		return (M)this;
	}

	public java.lang.Integer getSortId() {
		return getInt("sortId");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public M setCreateTime(java.lang.String createTime) {
		set("createTime", createTime);
		return (M)this;
	}

	public java.lang.String getCreateTime() {
		return getStr("createTime");
	}

}
