package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseXmlySound<M extends BaseXmlySound<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setSoundId(java.lang.Integer soundId) {
		set("soundId", soundId);
		return (M)this;
	}

	public java.lang.Integer getSoundId() {
		return getInt("soundId");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return getStr("name");
	}

	public M setImage(java.lang.String image) {
		set("image", image);
		return (M)this;
	}

	public java.lang.String getImage() {
		return getStr("image");
	}

	public M setIntro(java.lang.String intro) {
		set("intro", intro);
		return (M)this;
	}

	public java.lang.String getIntro() {
		return getStr("intro");
	}

	public M setPlayTimes(java.lang.Integer playTimes) {
		set("playTimes", playTimes);
		return (M)this;
	}

	public java.lang.Integer getPlayTimes() {
		return getInt("playTimes");
	}

	public M setPlayUrl(java.lang.String playUrl) {
		set("playUrl", playUrl);
		return (M)this;
	}

	public java.lang.String getPlayUrl() {
		return getStr("playUrl");
	}

	public M setUpdateTime(java.lang.String updateTime) {
		set("updateTime", updateTime);
		return (M)this;
	}

	public java.lang.String getUpdateTime() {
		return getStr("updateTime");
	}

	public M setAlbumName(java.lang.String albumName) {
		set("albumName", albumName);
		return (M)this;
	}

	public java.lang.String getAlbumName() {
		return getStr("albumName");
	}

	public M setChannelId(java.lang.Integer channelId) {
		set("channelId", channelId);
		return (M)this;
	}

	public java.lang.Integer getChannelId() {
		return getInt("channelId");
	}

	public M setAlbumId(java.lang.Integer albumId) {
		set("albumId", albumId);
		return (M)this;
	}

	public java.lang.Integer getAlbumId() {
		return getInt("albumId");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public M setSortId(java.lang.Integer sortId) {
		set("sortId", sortId);
		return (M)this;
	}

	public java.lang.Integer getSortId() {
		return getInt("sortId");
	}

	public M setCateId(java.lang.String cateId) {
		set("cate_id", cateId);
		return (M)this;
	}

	public java.lang.String getCateId() {
		return getStr("cate_id");
	}

	public M setScore(java.lang.Integer score) {
		set("score", score);
		return (M)this;
	}

	public java.lang.Integer getScore() {
		return getInt("score");
	}

	public M setFdPlaycount(java.lang.Integer fdPlaycount) {
		set("fd_playCount", fdPlaycount);
		return (M)this;
	}

	public java.lang.Integer getFdPlaycount() {
		return getInt("fd_playCount");
	}

	public M setProcess(java.lang.Integer process) {
		set("process", process);
		return (M)this;
	}

	public java.lang.Integer getProcess() {
		return getInt("process");
	}

}
