package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseShoppingcart<M extends BaseShoppingcart<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setProductid(java.lang.Integer productid) {
		set("productid", productid);
		return (M)this;
	}

	public java.lang.Integer getProductid() {
		return getInt("productid");
	}

	public M setSpecifications(java.lang.String specifications) {
		set("specifications", specifications);
		return (M)this;
	}

	public java.lang.String getSpecifications() {
		return getStr("specifications");
	}

	public M setProductname(java.lang.String productname) {
		set("productname", productname);
		return (M)this;
	}

	public java.lang.String getProductname() {
		return getStr("productname");
	}

	public M setProductimg(java.lang.String productimg) {
		set("productimg", productimg);
		return (M)this;
	}

	public java.lang.String getProductimg() {
		return getStr("productimg");
	}

	public M setPrice(java.lang.Double price) {
		set("price", price);
		return (M)this;
	}

	public java.lang.Double getPrice() {
		return getDouble("price");
	}

	public M setCount(java.lang.Integer count) {
		set("count", count);
		return (M)this;
	}

	public java.lang.Integer getCount() {
		return getInt("count");
	}

	public M setMemberid(java.lang.Integer memberid) {
		set("memberid", memberid);
		return (M)this;
	}

	public java.lang.Integer getMemberid() {
		return getInt("memberid");
	}

	public M setSpecificationsId(java.lang.Integer specificationsId) {
		set("specifications_id", specificationsId);
		return (M)this;
	}

	public java.lang.Integer getSpecificationsId() {
		return getInt("specifications_id");
	}

}
