package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDeviceShare<M extends BaseDeviceShare<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setDeviceNo(java.lang.String deviceNo) {
		set("device_no", deviceNo);
		return (M)this;
	}

	public java.lang.String getDeviceNo() {
		return getStr("device_no");
	}

	public M setEpalId(java.lang.String epalId) {
		set("epal_id", epalId);
		return (M)this;
	}

	public java.lang.String getEpalId() {
		return getStr("epal_id");
	}

	public M setShareUrl(java.lang.String shareUrl) {
		set("share_url", shareUrl);
		return (M)this;
	}

	public java.lang.String getShareUrl() {
		return getStr("share_url");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setShareTitle(java.lang.String shareTitle) {
		set("share_title", shareTitle);
		return (M)this;
	}

	public java.lang.String getShareTitle() {
		return getStr("share_title");
	}

	public M setFileType(java.lang.String fileType) {
		set("file_type", fileType);
		return (M)this;
	}

	public java.lang.String getFileType() {
		return getStr("file_type");
	}

	public M setPath(java.lang.String path) {
		set("path", path);
		return (M)this;
	}

	public java.lang.String getPath() {
		return getStr("path");
	}

}
