package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseWechatApi<M extends BaseWechatApi<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setApiUrl(java.lang.String apiUrl) {
		set("api_url", apiUrl);
		return (M)this;
	}

	public java.lang.String getApiUrl() {
		return getStr("api_url");
	}

	public M setMethod(java.lang.String method) {
		set("method", method);
		return (M)this;
	}

	public java.lang.String getMethod() {
		return getStr("method");
	}

	public M setParamter(java.lang.String paramter) {
		set("paramter", paramter);
		return (M)this;
	}

	public java.lang.String getParamter() {
		return getStr("paramter");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return getStr("name");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public M setModule(java.lang.String module) {
		set("module", module);
		return (M)this;
	}

	public java.lang.String getModule() {
		return getStr("module");
	}

	public M setPackage(java.lang.String _package) {
		set("package", _package);
		return (M)this;
	}

	public java.lang.String getPackage() {
		return getStr("package");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}

	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public M setLevel(java.lang.Integer level) {
		set("level", level);
		return (M)this;
	}

	public java.lang.Integer getLevel() {
		return getInt("level");
	}

}
