package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSpecial<M extends BaseSpecial<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setLogo(java.lang.String logo) {
		set("logo", logo);
		return (M)this;
	}

	public java.lang.String getLogo() {
		return getStr("logo");
	}

	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}

	public java.lang.String getTitle() {
		return getStr("title");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public M setSort(java.lang.Integer sort) {
		set("sort", sort);
		return (M)this;
	}

	public java.lang.Integer getSort() {
		return getInt("sort");
	}

	public M setCatId(java.lang.Integer catId) {
		set("cat_id", catId);
		return (M)this;
	}

	public java.lang.Integer getCatId() {
		return getInt("cat_id");
	}

	public M setTopicType(java.lang.Integer topicType) {
		set("topic_type", topicType);
		return (M)this;
	}

	public java.lang.Integer getTopicType() {
		return getInt("topic_type");
	}

}
