package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCourseprojectActive<M extends BaseCourseprojectActive<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setQrcodeUrl(java.lang.String qrcodeUrl) {
		set("qrcode_url", qrcodeUrl);
		return (M)this;
	}

	public java.lang.String getQrcodeUrl() {
		return getStr("qrcode_url");
	}

	public M setQrcodeContent(java.lang.String qrcodeContent) {
		set("qrcode_content", qrcodeContent);
		return (M)this;
	}

	public java.lang.String getQrcodeContent() {
		return getStr("qrcode_content");
	}

	public M setPlanId(java.lang.Integer planId) {
		set("plan_id", planId);
		return (M)this;
	}

	public java.lang.Integer getPlanId() {
		return getInt("plan_id");
	}

	public M setPlanName(java.lang.String planName) {
		set("plan_name", planName);
		return (M)this;
	}

	public java.lang.String getPlanName() {
		return getStr("plan_name");
	}

	public M setActiveCount(java.lang.Integer activeCount) {
		set("active_count", activeCount);
		return (M)this;
	}

	public java.lang.Integer getActiveCount() {
		return getInt("active_count");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
