package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseClassCourseScoreRecord<M extends BaseClassCourseScoreRecord<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setClasscourserecordId(java.lang.Integer classcourserecordId) {
		set("classCourseRecord_id", classcourserecordId);
		return (M)this;
	}

	public java.lang.Integer getClasscourserecordId() {
		return getInt("classCourseRecord_id");
	}

	public M setScore(java.lang.String score) {
		set("score", score);
		return (M)this;
	}

	public java.lang.String getScore() {
		return getStr("score");
	}

	public M setAudioUrl(java.lang.String audioUrl) {
		set("audioUrl", audioUrl);
		return (M)this;
	}

	public java.lang.String getAudioUrl() {
		return getStr("audioUrl");
	}

	public M setInsertDate(java.lang.String insertDate) {
		set("insertDate", insertDate);
		return (M)this;
	}

	public java.lang.String getInsertDate() {
		return getStr("insertDate");
	}

	public M setRecordDate(java.lang.String recordDate) {
		set("recordDate", recordDate);
		return (M)this;
	}

	public java.lang.String getRecordDate() {
		return getStr("recordDate");
	}

	public M setType(java.lang.String type) {
		set("type", type);
		return (M)this;
	}

	public java.lang.String getType() {
		return getStr("type");
	}

	public M setAccuracy(java.lang.String accuracy) {
		set("accuracy", accuracy);
		return (M)this;
	}

	public java.lang.String getAccuracy() {
		return getStr("accuracy");
	}

	public M setIntegrity(java.lang.String integrity) {
		set("integrity", integrity);
		return (M)this;
	}

	public java.lang.String getIntegrity() {
		return getStr("integrity");
	}

	public M setFluency(java.lang.String fluency) {
		set("fluency", fluency);
		return (M)this;
	}

	public java.lang.String getFluency() {
		return getStr("fluency");
	}

	public M setTimeCost(java.lang.String timeCost) {
		set("timeCost", timeCost);
		return (M)this;
	}

	public java.lang.String getTimeCost() {
		return getStr("timeCost");
	}

	public M setWordList(java.lang.String wordList) {
		set("wordList", wordList);
		return (M)this;
	}

	public java.lang.String getWordList() {
		return getStr("wordList");
	}

}
