package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSchoolCreditRecord<M extends BaseSchoolCreditRecord<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setSchoolId(java.lang.Integer schoolId) {
		set("school_id", schoolId);
		return (M)this;
	}

	public java.lang.Integer getSchoolId() {
		return getInt("school_id");
	}

	public M setAction(java.lang.Integer action) {
		set("action", action);
		return (M)this;
	}

	public java.lang.Integer getAction() {
		return getInt("action");
	}

	public M setAmount(java.lang.Long amount) {
		set("amount", amount);
		return (M)this;
	}

	public java.lang.Long getAmount() {
		return getLong("amount");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
