package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCategory123<M extends BaseCategory123<M>> extends Model<M> implements IBean {

	public M setCateID(java.lang.String cateID) {
		set("cateID", cateID);
		return (M)this;
	}

	public java.lang.String getCateID() {
		return getStr("cateID");
	}

	public M setBname(java.lang.String bname) {
		set("bname", bname);
		return (M)this;
	}

	public java.lang.String getBname() {
		return getStr("bname");
	}

	public M setPrice(java.lang.Double price) {
		set("price", price);
		return (M)this;
	}

	public java.lang.Double getPrice() {
		return getDouble("price");
	}

	public M setPublish(java.lang.String publish) {
		set("publish", publish);
		return (M)this;
	}

	public java.lang.String getPublish() {
		return getStr("publish");
	}

	public M setAuthor(java.lang.String author) {
		set("author", author);
		return (M)this;
	}

	public java.lang.String getAuthor() {
		return getStr("author");
	}

	public M setTranslator(java.lang.String translator) {
		set("translator", translator);
		return (M)this;
	}

	public java.lang.String getTranslator() {
		return getStr("translator");
	}

	public M setPage(java.lang.Integer page) {
		set("page", page);
		return (M)this;
	}

	public java.lang.Integer getPage() {
		return getInt("page");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}

	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public M setCover(java.lang.String cover) {
		set("cover", cover);
		return (M)this;
	}

	public java.lang.String getCover() {
		return getStr("cover");
	}

	public M setContent(java.lang.String content) {
		set("content", content);
		return (M)this;
	}

	public java.lang.String getContent() {
		return getStr("content");
	}

	public M setCount(java.lang.Integer count) {
		set("count", count);
		return (M)this;
	}

	public java.lang.Integer getCount() {
		return getInt("count");
	}

	public M setBquantity(java.lang.Integer bquantity) {
		set("bquantity", bquantity);
		return (M)this;
	}

	public java.lang.Integer getBquantity() {
		return getInt("bquantity");
	}

	public M setRightId(java.lang.Integer rightId) {
		set("right_id", rightId);
		return (M)this;
	}

	public java.lang.Integer getRightId() {
		return getInt("right_id");
	}

	public M setSeries(java.lang.String series) {
		set("series", series);
		return (M)this;
	}

	public java.lang.String getSeries() {
		return getStr("series");
	}

	public M setMp3(java.lang.String mp3) {
		set("mp3", mp3);
		return (M)this;
	}

	public java.lang.String getMp3() {
		return getStr("mp3");
	}

	public M setTestmp3(java.lang.String testmp3) {
		set("testmp3", testmp3);
		return (M)this;
	}

	public java.lang.String getTestmp3() {
		return getStr("testmp3");
	}

	public M setCatalog(java.lang.String catalog) {
		set("catalog", catalog);
		return (M)this;
	}

	public java.lang.String getCatalog() {
		return getStr("catalog");
	}

	public M setCode(java.lang.String code) {
		set("code", code);
		return (M)this;
	}

	public java.lang.String getCode() {
		return getStr("code");
	}

	public M setMp3type(java.lang.Integer mp3type) {
		set("mp3type", mp3type);
		return (M)this;
	}

	public java.lang.Integer getMp3type() {
		return getInt("mp3type");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public M setBookCateId(java.lang.Integer bookCateId) {
		set("book_cate_id", bookCateId);
		return (M)this;
	}

	public java.lang.Integer getBookCateId() {
		return getInt("book_cate_id");
	}

}
