package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseLiveScriptStatus<M extends BaseLiveScriptStatus<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setCourseId(java.lang.Integer courseId) {
		set("course_id", courseId);
		return (M)this;
	}

	public java.lang.Integer getCourseId() {
		return getInt("course_id");
	}

	public M setClassScriptId(java.lang.Integer classScriptId) {
		set("class_script_id", classScriptId);
		return (M)this;
	}

	public java.lang.Integer getClassScriptId() {
		return getInt("class_script_id");
	}

	public M setLiveStatus(java.lang.Integer liveStatus) {
		set("live_status", liveStatus);
		return (M)this;
	}

	public java.lang.Integer getLiveStatus() {
		return getInt("live_status");
	}

}
