package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseEvalWxUser<M extends BaseEvalWxUser<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public M setSort(java.lang.Integer sort) {
		set("sort", sort);
		return (M)this;
	}

	public java.lang.Integer getSort() {
		return getInt("sort");
	}

	public M setCreatTime(java.util.Date creatTime) {
		set("creat_time", creatTime);
		return (M)this;
	}

	public java.util.Date getCreatTime() {
		return get("creat_time");
	}

	public M setEditTime(java.util.Date editTime) {
		set("edit_time", editTime);
		return (M)this;
	}

	public java.util.Date getEditTime() {
		return get("edit_time");
	}

	public M setOpenId(java.lang.String openId) {
		set("open_id", openId);
		return (M)this;
	}

	public java.lang.String getOpenId() {
		return getStr("open_id");
	}

	public M setChildName(java.lang.String childName) {
		set("child_name", childName);
		return (M)this;
	}

	public java.lang.String getChildName() {
		return getStr("child_name");
	}

	public M setChildAge(java.lang.Integer childAge) {
		set("child_age", childAge);
		return (M)this;
	}

	public java.lang.Integer getChildAge() {
		return getInt("child_age");
	}

	public M setChildGrade(java.lang.String childGrade) {
		set("child_grade", childGrade);
		return (M)this;
	}

	public java.lang.String getChildGrade() {
		return getStr("child_grade");
	}

	public M setChildNickName(java.lang.String childNickName) {
		set("child_nick_name", childNickName);
		return (M)this;
	}

	public java.lang.String getChildNickName() {
		return getStr("child_nick_name");
	}

	public M setParentPhone(java.lang.String parentPhone) {
		set("parent_phone", parentPhone);
		return (M)this;
	}

	public java.lang.String getParentPhone() {
		return getStr("parent_phone");
	}

	public M setMemberId(java.lang.String memberId) {
		set("memberId", memberId);
		return (M)this;
	}

	public java.lang.String getMemberId() {
		return getStr("memberId");
	}

}
