package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMallorderservice<M extends BaseMallorderservice<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setOrderid(java.lang.Integer orderid) {
		set("orderid", orderid);
		return (M)this;
	}

	public java.lang.Integer getOrderid() {
		return getInt("orderid");
	}

	public M setOrdernumber(java.lang.String ordernumber) {
		set("ordernumber", ordernumber);
		return (M)this;
	}

	public java.lang.String getOrdernumber() {
		return getStr("ordernumber");
	}

	public M setMemberId(java.lang.Integer memberId) {
		set("memberId", memberId);
		return (M)this;
	}

	public java.lang.Integer getMemberId() {
		return getInt("memberId");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}

	public java.lang.Integer getType() {
		return getInt("type");
	}

	public M setCreatedate(java.util.Date createdate) {
		set("createdate", createdate);
		return (M)this;
	}

	public java.util.Date getCreatedate() {
		return get("createdate");
	}

	public M setPayment(java.lang.Double payment) {
		set("payment", payment);
		return (M)this;
	}

	public java.lang.Double getPayment() {
		return getDouble("payment");
	}

	public M setRemarks(java.lang.String remarks) {
		set("remarks", remarks);
		return (M)this;
	}

	public java.lang.String getRemarks() {
		return getStr("remarks");
	}

	public M setExpress(java.lang.String express) {
		set("express", express);
		return (M)this;
	}

	public java.lang.String getExpress() {
		return getStr("express");
	}

	public M setExpressnumber(java.lang.String expressnumber) {
		set("expressnumber", expressnumber);
		return (M)this;
	}

	public java.lang.String getExpressnumber() {
		return getStr("expressnumber");
	}

	public M setOperatorid(java.lang.Integer operatorid) {
		set("operatorid", operatorid);
		return (M)this;
	}

	public java.lang.Integer getOperatorid() {
		return getInt("operatorid");
	}

	public M setServicetype(java.lang.String servicetype) {
		set("servicetype", servicetype);
		return (M)this;
	}

	public java.lang.String getServicetype() {
		return getStr("servicetype");
	}

}
