package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseClassRoomLabel<M extends BaseClassRoomLabel<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setLabelName(java.lang.String labelName) {
		set("label_name", labelName);
		return (M)this;
	}

	public java.lang.String getLabelName() {
		return getStr("label_name");
	}

	public M setSortId(java.lang.Integer sortId) {
		set("sort_id", sortId);
		return (M)this;
	}

	public java.lang.Integer getSortId() {
		return getInt("sort_id");
	}

	public M setGroupId(java.lang.Integer groupId) {
		set("group_id", groupId);
		return (M)this;
	}

	public java.lang.Integer getGroupId() {
		return getInt("group_id");
	}

	public M setIsShow(java.lang.String isShow) {
		set("is_show", isShow);
		return (M)this;
	}

	public java.lang.String getIsShow() {
		return getStr("is_show");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.Integer getStatus() {
		return getInt("status");
	}

}
