package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBulletinQuestion<M extends BaseBulletinQuestion<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}

	public java.lang.String getTitle() {
		return getStr("title");
	}

	public M setContent(java.lang.String content) {
		set("content", content);
		return (M)this;
	}

	public java.lang.String getContent() {
		return getStr("content");
	}

	public M setQuestionScriptContent(java.lang.String questionScriptContent) {
		set("question_script_content", questionScriptContent);
		return (M)this;
	}

	public java.lang.String getQuestionScriptContent() {
		return getStr("question_script_content");
	}

	public M setMemberId(java.lang.Integer memberId) {
		set("member_id", memberId);
		return (M)this;
	}

	public java.lang.Integer getMemberId() {
		return getInt("member_id");
	}

	public M setStudentId(java.lang.Integer studentId) {
		set("student_id", studentId);
		return (M)this;
	}

	public java.lang.Integer getStudentId() {
		return getInt("student_id");
	}

	public M setRewardIntegral(java.lang.Integer rewardIntegral) {
		set("reward_integral", rewardIntegral);
		return (M)this;
	}

	public java.lang.Integer getRewardIntegral() {
		return getInt("reward_integral");
	}

	public M setIsClose(java.lang.Integer isClose) {
		set("is_close", isClose);
		return (M)this;
	}

	public java.lang.Integer getIsClose() {
		return getInt("is_close");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public M setBReply(java.lang.Integer bReply) {
		set("b_reply", bReply);
		return (M)this;
	}

	public java.lang.Integer getBReply() {
		return getInt("b_reply");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
