package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCity<M extends BaseCity<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.String getId() {
		return getStr("id");
	}

	public M setCodeC(java.lang.String codeC) {
		set("code_c", codeC);
		return (M)this;
	}

	public java.lang.String getCodeC() {
		return getStr("code_c");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return getStr("name");
	}

	public M setCodeP(java.lang.String codeP) {
		set("code_p", codeP);
		return (M)this;
	}

	public java.lang.String getCodeP() {
		return getStr("code_p");
	}

}
