package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAppidSecret<M extends BaseAppidSecret<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setAppid(java.lang.String appid) {
		set("appid", appid);
		return (M)this;
	}

	public java.lang.String getAppid() {
		return getStr("appid");
	}

	public M setSecret(java.lang.String secret) {
		set("secret", secret);
		return (M)this;
	}

	public java.lang.String getSecret() {
		return getStr("secret");
	}

	public M setLibraryId(java.lang.Integer libraryId) {
		set("library_id", libraryId);
		return (M)this;
	}

	public java.lang.Integer getLibraryId() {
		return getInt("library_id");
	}

}
