package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseIntegralCopy<M extends BaseIntegralCopy<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}

	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public M setTypeid(java.lang.Integer typeid) {
		set("typeid", typeid);
		return (M)this;
	}

	public java.lang.Integer getTypeid() {
		return getInt("typeid");
	}

	public M setMemberid(java.lang.Integer memberid) {
		set("memberid", memberid);
		return (M)this;
	}

	public java.lang.Integer getMemberid() {
		return getInt("memberid");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public M setFraction(java.lang.Integer fraction) {
		set("fraction", fraction);
		return (M)this;
	}

	public java.lang.Integer getFraction() {
		return getInt("fraction");
	}

	public M setCreatedate(java.util.Date createdate) {
		set("createdate", createdate);
		return (M)this;
	}

	public java.util.Date getCreatedate() {
		return get("createdate");
	}

	public M setMembertype(java.lang.Integer membertype) {
		set("membertype", membertype);
		return (M)this;
	}

	public java.lang.Integer getMembertype() {
		return getInt("membertype");
	}

}
