package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseProductPay<M extends BaseProductPay<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setUser(java.lang.String user) {
		set("user", user);
		return (M)this;
	}

	public java.lang.String getUser() {
		return getStr("user");
	}

	public M setPhone(java.lang.String phone) {
		set("phone", phone);
		return (M)this;
	}

	public java.lang.String getPhone() {
		return getStr("phone");
	}

	public M setGrade(java.lang.String grade) {
		set("grade", grade);
		return (M)this;
	}

	public java.lang.String getGrade() {
		return getStr("grade");
	}

	public M setOrderNumber(java.lang.String orderNumber) {
		set("orderNumber", orderNumber);
		return (M)this;
	}

	public java.lang.String getOrderNumber() {
		return getStr("orderNumber");
	}

	public M setOpenid(java.lang.String openid) {
		set("openid", openid);
		return (M)this;
	}

	public java.lang.String getOpenid() {
		return getStr("openid");
	}

	public M setPrice(java.math.BigDecimal price) {
		set("price", price);
		return (M)this;
	}

	public java.math.BigDecimal getPrice() {
		return get("price");
	}

	public M setProductSpec(java.lang.String productSpec) {
		set("product_spec", productSpec);
		return (M)this;
	}

	public java.lang.String getProductSpec() {
		return getStr("product_spec");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
