package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDeviceStudy<M extends BaseDeviceStudy<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setDeviceNo(java.lang.String deviceNo) {
		set("device_no", deviceNo);
		return (M)this;
	}

	public java.lang.String getDeviceNo() {
		return getStr("device_no");
	}

	public M setEpalId(java.lang.String epalId) {
		set("epal_id", epalId);
		return (M)this;
	}

	public java.lang.String getEpalId() {
		return getStr("epal_id");
	}

	public M setMissionId(java.lang.String missionId) {
		set("mission_id", missionId);
		return (M)this;
	}

	public java.lang.String getMissionId() {
		return getStr("mission_id");
	}

	public M setMissionName(java.lang.String missionName) {
		set("mission_name", missionName);
		return (M)this;
	}

	public java.lang.String getMissionName() {
		return getStr("mission_name");
	}

	public M setContent(java.lang.String content) {
		set("content", content);
		return (M)this;
	}

	public java.lang.String getContent() {
		return getStr("content");
	}

	public M setIsdone(java.lang.Integer isdone) {
		set("isdone", isdone);
		return (M)this;
	}

	public java.lang.Integer getIsdone() {
		return getInt("isdone");
	}

	public M setUrl(java.lang.String url) {
		set("url", url);
		return (M)this;
	}

	public java.lang.String getUrl() {
		return getStr("url");
	}

}
