package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseVideoScore<M extends BaseVideoScore<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setVideoInfoId(java.lang.Integer videoInfoId) {
		set("video_info_id", videoInfoId);
		return (M)this;
	}

	public java.lang.Integer getVideoInfoId() {
		return getInt("video_info_id");
	}

	public M setExpert1(java.lang.String expert1) {
		set("expert1", expert1);
		return (M)this;
	}

	public java.lang.String getExpert1() {
		return getStr("expert1");
	}

	public M setExpert2(java.lang.String expert2) {
		set("expert2", expert2);
		return (M)this;
	}

	public java.lang.String getExpert2() {
		return getStr("expert2");
	}

	public M setExpert3(java.lang.String expert3) {
		set("expert3", expert3);
		return (M)this;
	}

	public java.lang.String getExpert3() {
		return getStr("expert3");
	}

	public M setExpert4(java.lang.String expert4) {
		set("expert4", expert4);
		return (M)this;
	}

	public java.lang.String getExpert4() {
		return getStr("expert4");
	}

	public M setCreatTime(java.util.Date creatTime) {
		set("creat_time", creatTime);
		return (M)this;
	}

	public java.util.Date getCreatTime() {
		return get("creat_time");
	}

	public M setEditTime(java.util.Date editTime) {
		set("edit_time", editTime);
		return (M)this;
	}

	public java.util.Date getEditTime() {
		return get("edit_time");
	}

}
