package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseIntegralLevelInfo<M extends BaseIntegralLevelInfo<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setLevelName(java.lang.String levelName) {
		set("level_name", levelName);
		return (M)this;
	}

	public java.lang.String getLevelName() {
		return getStr("level_name");
	}

	public M setLevel(java.lang.Integer level) {
		set("level", level);
		return (M)this;
	}

	public java.lang.Integer getLevel() {
		return getInt("level");
	}

	public M setIntegralStart(java.lang.Integer integralStart) {
		set("integral_start", integralStart);
		return (M)this;
	}

	public java.lang.Integer getIntegralStart() {
		return getInt("integral_start");
	}

	public M setIntegralEnd(java.lang.Integer integralEnd) {
		set("integral_end", integralEnd);
		return (M)this;
	}

	public java.lang.Integer getIntegralEnd() {
		return getInt("integral_end");
	}

	public M setLevelPicUrl(java.lang.String levelPicUrl) {
		set("level_pic_url", levelPicUrl);
		return (M)this;
	}

	public java.lang.String getLevelPicUrl() {
		return getStr("level_pic_url");
	}

	public M setLevelUrl(java.lang.String levelUrl) {
		set("level_url", levelUrl);
		return (M)this;
	}

	public java.lang.String getLevelUrl() {
		return getStr("level_url");
	}

}
