package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDriver<M extends BaseDriver<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return getStr("name");
	}

	public M setIdCard(java.lang.String idCard) {
		set("id_card", idCard);
		return (M)this;
	}

	public java.lang.String getIdCard() {
		return getStr("id_card");
	}

	public M setAddress(java.lang.String address) {
		set("address", address);
		return (M)this;
	}

	public java.lang.String getAddress() {
		return getStr("address");
	}

	public M setMotorcade(java.lang.String motorcade) {
		set("motorcade", motorcade);
		return (M)this;
	}

	public java.lang.String getMotorcade() {
		return getStr("motorcade");
	}

	public M setTelphone(java.lang.String telphone) {
		set("telphone", telphone);
		return (M)this;
	}

	public java.lang.String getTelphone() {
		return getStr("telphone");
	}

	public M setJoinDate(java.util.Date joinDate) {
		set("join_date", joinDate);
		return (M)this;
	}

	public java.util.Date getJoinDate() {
		return get("join_date");
	}

	public M setAvatar(java.lang.String avatar) {
		set("avatar", avatar);
		return (M)this;
	}

	public java.lang.String getAvatar() {
		return getStr("avatar");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
