package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePushHistory<M extends BasePushHistory<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setSourceId(java.lang.Integer sourceId) {
		set("source_id", sourceId);
		return (M)this;
	}

	public java.lang.Integer getSourceId() {
		return getInt("source_id");
	}

	public M setSourceName(java.lang.String sourceName) {
		set("source_name", sourceName);
		return (M)this;
	}

	public java.lang.String getSourceName() {
		return getStr("source_name");
	}

	public M setSourceUrl(java.lang.String sourceUrl) {
		set("source_url", sourceUrl);
		return (M)this;
	}

	public java.lang.String getSourceUrl() {
		return getStr("source_url");
	}

	public M setSource(java.lang.String source) {
		set("source", source);
		return (M)this;
	}

	public java.lang.String getSource() {
		return getStr("source");
	}

	public M setTimes(java.lang.Integer times) {
		set("times", times);
		return (M)this;
	}

	public java.lang.Integer getTimes() {
		return getInt("times");
	}

	public M setUserId(java.lang.String userId) {
		set("user_id", userId);
		return (M)this;
	}

	public java.lang.String getUserId() {
		return getStr("user_id");
	}

	public M setEpalId(java.lang.String epalId) {
		set("epal_id", epalId);
		return (M)this;
	}

	public java.lang.String getEpalId() {
		return getStr("epal_id");
	}

	public M setPushTime(java.util.Date pushTime) {
		set("push_time", pushTime);
		return (M)this;
	}

	public java.util.Date getPushTime() {
		return get("push_time");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.Integer getStatus() {
		return getInt("status");
	}

}
