package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSoundAlias<M extends BaseSoundAlias<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setAliasName(java.lang.String aliasName) {
		set("aliasName", aliasName);
		return (M)this;
	}

	public java.lang.String getAliasName() {
		return getStr("aliasName");
	}

	public M setSoundId(java.lang.Integer soundId) {
		set("soundId", soundId);
		return (M)this;
	}

	public java.lang.Integer getSoundId() {
		return getInt("soundId");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.Integer getStatus() {
		return getInt("status");
	}

}
