package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseVideoInfo<M extends BaseVideoInfo<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setVTitle(java.lang.String vTitle) {
		set("v_title", vTitle);
		return (M)this;
	}

	public java.lang.String getVTitle() {
		return getStr("v_title");
	}

	public M setVUrl(java.lang.String vUrl) {
		set("v_url", vUrl);
		return (M)this;
	}

	public java.lang.String getVUrl() {
		return getStr("v_url");
	}

	public M setPicUrl(java.lang.String picUrl) {
		set("pic_url", picUrl);
		return (M)this;
	}

	public java.lang.String getPicUrl() {
		return getStr("pic_url");
	}

	public M setStudentId(java.lang.Integer studentId) {
		set("student_id", studentId);
		return (M)this;
	}

	public java.lang.Integer getStudentId() {
		return getInt("student_id");
	}

	public M setSName(java.lang.String sName) {
		set("s_name", sName);
		return (M)this;
	}

	public java.lang.String getSName() {
		return getStr("s_name");
	}

	public M setLocalfileId(java.lang.String localfileId) {
		set("localfile_id", localfileId);
		return (M)this;
	}

	public java.lang.String getLocalfileId() {
		return getStr("localfile_id");
	}

	public M setShareUrl(java.lang.String shareUrl) {
		set("share_url", shareUrl);
		return (M)this;
	}

	public java.lang.String getShareUrl() {
		return getStr("share_url");
	}

	public M setEpalId(java.lang.String epalId) {
		set("epal_id", epalId);
		return (M)this;
	}

	public java.lang.String getEpalId() {
		return getStr("epal_id");
	}

	public M setAcountId(java.lang.String acountId) {
		set("acount_id", acountId);
		return (M)this;
	}

	public java.lang.String getAcountId() {
		return getStr("acount_id");
	}

	public M setModifyTime(java.util.Date modifyTime) {
		set("modify_time", modifyTime);
		return (M)this;
	}

	public java.util.Date getModifyTime() {
		return get("modify_time");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setAdmission(java.lang.Integer admission) {
		set("admission", admission);
		return (M)this;
	}

	public java.lang.Integer getAdmission() {
		return getInt("admission");
	}

	public M setVote(java.lang.Integer vote) {
		set("vote", vote);
		return (M)this;
	}

	public java.lang.Integer getVote() {
		return getInt("vote");
	}

	public M setAccessNum(java.lang.Integer accessNum) {
		set("access_num", accessNum);
		return (M)this;
	}

	public java.lang.Integer getAccessNum() {
		return getInt("access_num");
	}

	public M setVideoScoreId(java.lang.Integer videoScoreId) {
		set("video_score_id", videoScoreId);
		return (M)this;
	}

	public java.lang.Integer getVideoScoreId() {
		return getInt("video_score_id");
	}

	public M setVLike(java.lang.Integer vLike) {
		set("v_like", vLike);
		return (M)this;
	}

	public java.lang.Integer getVLike() {
		return getInt("v_like");
	}

	public M setVReward(java.lang.Double vReward) {
		set("v_reward", vReward);
		return (M)this;
	}

	public java.lang.Double getVReward() {
		return getDouble("v_reward");
	}

	public M setLearnTime(java.lang.String learnTime) {
		set("learn_time", learnTime);
		return (M)this;
	}

	public java.lang.String getLearnTime() {
		return getStr("learn_time");
	}

	public M setCommentStatus(java.lang.Integer commentStatus) {
		set("comment_status", commentStatus);
		return (M)this;
	}

	public java.lang.Integer getCommentStatus() {
		return getInt("comment_status");
	}

	public M setVideoDescription(java.lang.String videoDescription) {
		set("video_description", videoDescription);
		return (M)this;
	}

	public java.lang.String getVideoDescription() {
		return getStr("video_description");
	}

	public M setIsQuote(java.lang.Integer isQuote) {
		set("is_quote", isQuote);
		return (M)this;
	}

	public java.lang.Integer getIsQuote() {
		return getInt("is_quote");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public M setLearnDay(java.lang.Integer learnDay) {
		set("learn_day", learnDay);
		return (M)this;
	}

	public java.lang.Integer getLearnDay() {
		return getInt("learn_day");
	}

}
