package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseFolderAgent<M extends BaseFolderAgent<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer Id) {
		set("Id", Id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("Id");
	}

	public M setFolderName(java.lang.String folderName) {
		set("folder_name", folderName);
		return (M)this;
	}

	public java.lang.String getFolderName() {
		return getStr("folder_name");
	}

	public M setFolderType(java.lang.String folderType) {
		set("folder_type", folderType);
		return (M)this;
	}

	public java.lang.String getFolderType() {
		return getStr("folder_type");
	}

	public M setFileLink(java.lang.String fileLink) {
		set("file_link", fileLink);
		return (M)this;
	}

	public java.lang.String getFileLink() {
		return getStr("file_link");
	}

	public M setCreatedate(java.util.Date createdate) {
		set("createdate", createdate);
		return (M)this;
	}

	public java.util.Date getCreatedate() {
		return get("createdate");
	}

	public M setHigherUp(java.lang.Integer higherUp) {
		set("higher_up", higherUp);
		return (M)this;
	}

	public java.lang.Integer getHigherUp() {
		return getInt("higher_up");
	}

}
