package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSoundRecommendGroup<M extends BaseSoundRecommendGroup<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setTagEN(java.lang.String tagEN) {
		set("tagEN", tagEN);
		return (M)this;
	}

	public java.lang.String getTagEN() {
		return getStr("tagEN");
	}

	public M setChannelId(java.lang.Integer channelId) {
		set("channelId", channelId);
		return (M)this;
	}

	public java.lang.Integer getChannelId() {
		return getInt("channelId");
	}

	public M setTagCN(java.lang.String tagCN) {
		set("tagCN", tagCN);
		return (M)this;
	}

	public java.lang.String getTagCN() {
		return getStr("tagCN");
	}

}
