package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCourseBooklib<M extends BaseCourseBooklib<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setProductid(java.lang.Integer productid) {
		set("productid", productid);
		return (M)this;
	}

	public java.lang.Integer getProductid() {
		return getInt("productid");
	}

	public M setBookname(java.lang.String bookname) {
		set("bookname", bookname);
		return (M)this;
	}

	public java.lang.String getBookname() {
		return getStr("bookname");
	}

	public M setBookcover(java.lang.String bookcover) {
		set("bookcover", bookcover);
		return (M)this;
	}

	public java.lang.String getBookcover() {
		return getStr("bookcover");
	}

	public M setBookisbn(java.lang.String bookisbn) {
		set("bookisbn", bookisbn);
		return (M)this;
	}

	public java.lang.String getBookisbn() {
		return getStr("bookisbn");
	}

}
