package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseHotKeys<M extends BaseHotKeys<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setKeys(java.lang.String keys) {
		set("keys", keys);
		return (M)this;
	}

	public java.lang.String getKeys() {
		return getStr("keys");
	}

	public M setKeyType(java.lang.String keyType) {
		set("key_type", keyType);
		return (M)this;
	}

	public java.lang.String getKeyType() {
		return getStr("key_type");
	}

	public M setScore(java.lang.Integer score) {
		set("score", score);
		return (M)this;
	}

	public java.lang.Integer getScore() {
		return getInt("score");
	}

}
