package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMember1<M extends BaseMember1<M>> extends Model<M> implements IBean {

	public M setUsername(java.lang.String username) {
		set("username", username);
		return (M)this;
	}

	public java.lang.String getUsername() {
		return getStr("username");
	}

	public M setPassword(java.lang.String password) {
		set("password", password);
		return (M)this;
	}

	public java.lang.String getPassword() {
		return getStr("password");
	}

	public M setBarcode(java.lang.String barcode) {
		set("barcode", barcode);
		return (M)this;
	}

	public java.lang.String getBarcode() {
		return getStr("barcode");
	}

	public M setNick(java.lang.String nick) {
		set("nick", nick);
		return (M)this;
	}

	public java.lang.String getNick() {
		return getStr("nick");
	}

	public M setBorrowed(java.lang.Integer borrowed) {
		set("borrowed", borrowed);
		return (M)this;
	}

	public java.lang.Integer getBorrowed() {
		return getInt("borrowed");
	}

	public M setBorrowedAmount(java.lang.Long borrowedAmount) {
		set("borrowed_amount", borrowedAmount);
		return (M)this;
	}

	public java.lang.Long getBorrowedAmount() {
		return getLong("borrowed_amount");
	}

	public M setIcon(java.lang.String icon) {
		set("icon", icon);
		return (M)this;
	}

	public java.lang.String getIcon() {
		return getStr("icon");
	}

	public M setIsmem(java.lang.Long ismem) {
		set("ismem", ismem);
		return (M)this;
	}

	public java.lang.Long getIsmem() {
		return getLong("ismem");
	}

	public M setBelong(java.lang.Integer belong) {
		set("belong", belong);
		return (M)this;
	}

	public java.lang.Integer getBelong() {
		return getInt("belong");
	}

	public M setMemtypeId(java.lang.Integer memtypeId) {
		set("memtype_id", memtypeId);
		return (M)this;
	}

	public java.lang.Integer getMemtypeId() {
		return getInt("memtype_id");
	}

	public M setPurchaseTime(java.util.Date purchaseTime) {
		set("purchase_time", purchaseTime);
		return (M)this;
	}

	public java.util.Date getPurchaseTime() {
		return get("purchase_time");
	}

	public M setDeposit(java.lang.Integer deposit) {
		set("deposit", deposit);
		return (M)this;
	}

	public java.lang.Integer getDeposit() {
		return getInt("deposit");
	}

}
