package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseClassRoomReplyPic<M extends BaseClassRoomReplyPic<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setClassRoomReplyId(java.lang.Integer classRoomReplyId) {
		set("class_room_reply_id", classRoomReplyId);
		return (M)this;
	}

	public java.lang.Integer getClassRoomReplyId() {
		return getInt("class_room_reply_id");
	}

	public M setPic(java.lang.String pic) {
		set("pic", pic);
		return (M)this;
	}

	public java.lang.String getPic() {
		return getStr("pic");
	}

}
