package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseOnlineClassDeleteStudentRecord<M extends BaseOnlineClassDeleteStudentRecord<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setStudentId(java.lang.Integer studentId) {
		set("student_id", studentId);
		return (M)this;
	}

	public java.lang.Integer getStudentId() {
		return getInt("student_id");
	}

	public M setTeacherId(java.lang.Integer teacherId) {
		set("teacher_id", teacherId);
		return (M)this;
	}

	public java.lang.Integer getTeacherId() {
		return getInt("teacher_id");
	}

	public M setGradesId(java.lang.Integer gradesId) {
		set("grades_id", gradesId);
		return (M)this;
	}

	public java.lang.Integer getGradesId() {
		return getInt("grades_id");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public M setInsertDate(java.lang.String insertDate) {
		set("insert_date", insertDate);
		return (M)this;
	}

	public java.lang.String getInsertDate() {
		return getStr("insert_date");
	}

	public M setEditDate(java.lang.String editDate) {
		set("edit_date", editDate);
		return (M)this;
	}

	public java.lang.String getEditDate() {
		return getStr("edit_date");
	}

}
