package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMembertype<M extends BaseMembertype<M>> extends Model<M> implements IBean {

	public M setMemtypeid(java.lang.Integer memtypeid) {
		set("memtypeid", memtypeid);
		return (M)this;
	}

	public java.lang.Integer getMemtypeid() {
		return getInt("memtypeid");
	}

	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}

	public java.lang.String getTitle() {
		return getStr("title");
	}

	public M setContent(java.lang.String content) {
		set("content", content);
		return (M)this;
	}

	public java.lang.String getContent() {
		return getStr("content");
	}

	public M setPrice(java.lang.Integer price) {
		set("price", price);
		return (M)this;
	}

	public java.lang.Integer getPrice() {
		return getInt("price");
	}

	public M setPicpath(java.lang.String picpath) {
		set("picpath", picpath);
		return (M)this;
	}

	public java.lang.String getPicpath() {
		return getStr("picpath");
	}

	public M setLendable(java.lang.Integer lendable) {
		set("lendable", lendable);
		return (M)this;
	}

	public java.lang.Integer getLendable() {
		return getInt("lendable");
	}

	public M setForfree(java.lang.Integer forfree) {
		set("forfree", forfree);
		return (M)this;
	}

	public java.lang.Integer getForfree() {
		return getInt("forfree");
	}

}
