package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMemBook<M extends BaseMemBook<M>> extends Model<M> implements IBean {

	public M setBBarcode(java.lang.String bBarcode) {
		set("b_barcode", bBarcode);
		return (M)this;
	}

	public java.lang.String getBBarcode() {
		return getStr("b_barcode");
	}

	public M setMBarcode(java.lang.String mBarcode) {
		set("m_barcode", mBarcode);
		return (M)this;
	}

	public java.lang.String getMBarcode() {
		return getStr("m_barcode");
	}

	public M setBorrDate(java.util.Date borrDate) {
		set("borrDate", borrDate);
		return (M)this;
	}

	public java.util.Date getBorrDate() {
		return get("borrDate");
	}

	public M setBackDate(java.util.Date backDate) {
		set("backDate", backDate);
		return (M)this;
	}

	public java.util.Date getBackDate() {
		return get("backDate");
	}

	public M setIfBack(java.lang.Integer ifBack) {
		set("ifBack", ifBack);
		return (M)this;
	}

	public java.lang.Integer getIfBack() {
		return getInt("ifBack");
	}

	public M setIsRenew(java.lang.Integer isRenew) {
		set("isRenew", isRenew);
		return (M)this;
	}

	public java.lang.Integer getIsRenew() {
		return getInt("isRenew");
	}

}
