package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDiscovery<M extends BaseDiscovery<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setUserId(java.lang.Integer userId) {
		set("user_id", userId);
		return (M)this;
	}

	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	public M setContent(java.lang.String content) {
		set("content", content);
		return (M)this;
	}

	public java.lang.String getContent() {
		return getStr("content");
	}

	public M setImages(java.lang.String images) {
		set("images", images);
		return (M)this;
	}

	public java.lang.String getImages() {
		return getStr("images");
	}

	public M setIsOpen(java.lang.Integer isOpen) {
		set("is_open", isOpen);
		return (M)this;
	}

	public java.lang.Integer getIsOpen() {
		return getInt("is_open");
	}

	public M setAgreeNum(java.lang.Integer agreeNum) {
		set("agree_num", agreeNum);
		return (M)this;
	}

	public java.lang.Integer getAgreeNum() {
		return getInt("agree_num");
	}

	public M setCommentNum(java.lang.Integer commentNum) {
		set("comment_num", commentNum);
		return (M)this;
	}

	public java.lang.Integer getCommentNum() {
		return getInt("comment_num");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
