package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseRandComment<M extends BaseRandComment<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setMomentId(java.lang.Integer momentId) {
		set("moment_id", momentId);
		return (M)this;
	}

	public java.lang.Integer getMomentId() {
		return getInt("moment_id");
	}

	public M setStudentId(java.lang.Integer studentId) {
		set("student_id", studentId);
		return (M)this;
	}

	public java.lang.Integer getStudentId() {
		return getInt("student_id");
	}

	public M setTeacherId(java.lang.Integer teacherId) {
		set("teacher_id", teacherId);
		return (M)this;
	}

	public java.lang.Integer getTeacherId() {
		return getInt("teacher_id");
	}

	public M setContent(java.lang.String content) {
		set("content", content);
		return (M)this;
	}

	public java.lang.String getContent() {
		return getStr("content");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("createDate", createDate);
		return (M)this;
	}

	public java.util.Date getCreateDate() {
		return get("createDate");
	}

	public M setAudioUrl(java.lang.String audioUrl) {
		set("audio_url", audioUrl);
		return (M)this;
	}

	public java.lang.String getAudioUrl() {
		return getStr("audio_url");
	}

	public M setAudioTime(java.lang.String audioTime) {
		set("audio_time", audioTime);
		return (M)this;
	}

	public java.lang.String getAudioTime() {
		return getStr("audio_time");
	}

}
