package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDeviceStudentSchool<M extends BaseDeviceStudentSchool<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return getStr("name");
	}

	public M setSex(java.lang.String sex) {
		set("sex", sex);
		return (M)this;
	}

	public java.lang.String getSex() {
		return getStr("sex");
	}

	public M setFandouAccount(java.lang.String fandouAccount) {
		set("fandouAccount", fandouAccount);
		return (M)this;
	}

	public java.lang.String getFandouAccount() {
		return getStr("fandouAccount");
	}

	public M setParentName(java.lang.String parentName) {
		set("parentName", parentName);
		return (M)this;
	}

	public java.lang.String getParentName() {
		return getStr("parentName");
	}

	public M setParentMobile(java.lang.String parentMobile) {
		set("parentMobile", parentMobile);
		return (M)this;
	}

	public java.lang.String getParentMobile() {
		return getStr("parentMobile");
	}

	public M setEpalId(java.lang.String epalId) {
		set("epalId", epalId);
		return (M)this;
	}

	public java.lang.String getEpalId() {
		return getStr("epalId");
	}

	public M setClassName(java.lang.String className) {
		set("className", className);
		return (M)this;
	}

	public java.lang.String getClassName() {
		return getStr("className");
	}

	public M setSchool(java.lang.String school) {
		set("school", school);
		return (M)this;
	}

	public java.lang.String getSchool() {
		return getStr("school");
	}

	public M setInsertDate(java.lang.String insertDate) {
		set("insertDate", insertDate);
		return (M)this;
	}

	public java.lang.String getInsertDate() {
		return getStr("insertDate");
	}

	public M setAddr(java.lang.String addr) {
		set("addr", addr);
		return (M)this;
	}

	public java.lang.String getAddr() {
		return getStr("addr");
	}

}
