package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAudioMaterialRel<M extends BaseAudioMaterialRel<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer Id) {
		set("Id", Id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("Id");
	}

	public M setAudioId(java.lang.Integer audioId) {
		set("audio_id", audioId);
		return (M)this;
	}

	public java.lang.Integer getAudioId() {
		return getInt("audio_id");
	}

	public M setMaterialId(java.lang.Integer materialId) {
		set("material_id", materialId);
		return (M)this;
	}

	public java.lang.Integer getMaterialId() {
		return getInt("material_id");
	}

	public M setMemberId(java.lang.Integer memberId) {
		set("member_id", memberId);
		return (M)this;
	}

	public java.lang.Integer getMemberId() {
		return getInt("member_id");
	}

}
