package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseChaozhiStudyFriend<M extends BaseChaozhiStudyFriend<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setMember1(java.lang.Integer member1) {
		set("member1", member1);
		return (M)this;
	}

	public java.lang.Integer getMember1() {
		return getInt("member1");
	}

	public M setMember2(java.lang.Integer member2) {
		set("member2", member2);
		return (M)this;
	}

	public java.lang.Integer getMember2() {
		return getInt("member2");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.Integer getStatus() {
		return getInt("status");
	}

}
