package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseClassLiveBooking<M extends BaseClassLiveBooking<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setScheduleId(java.lang.Integer scheduleId) {
		set("schedule_id", scheduleId);
		return (M)this;
	}

	public java.lang.Integer getScheduleId() {
		return getInt("schedule_id");
	}

	public M setStudentId(java.lang.Integer studentId) {
		set("student_id", studentId);
		return (M)this;
	}

	public java.lang.Integer getStudentId() {
		return getInt("student_id");
	}

	public M setMobile(java.lang.String mobile) {
		set("mobile", mobile);
		return (M)this;
	}

	public java.lang.String getMobile() {
		return getStr("mobile");
	}

	public M setAppointTime(java.lang.String appointTime) {
		set("appoint_time", appointTime);
		return (M)this;
	}

	public java.lang.String getAppointTime() {
		return getStr("appoint_time");
	}

	public M setSpareTime(java.lang.String spareTime) {
		set("spare_time", spareTime);
		return (M)this;
	}

	public java.lang.String getSpareTime() {
		return getStr("spare_time");
	}

	public M setSpareTime2(java.lang.String spareTime2) {
		set("spare_time2", spareTime2);
		return (M)this;
	}

	public java.lang.String getSpareTime2() {
		return getStr("spare_time2");
	}

	public M setClassTime(java.lang.String classTime) {
		set("class_time", classTime);
		return (M)this;
	}

	public java.lang.String getClassTime() {
		return getStr("class_time");
	}

	public M setTeacherName(java.lang.String teacherName) {
		set("teacher_name", teacherName);
		return (M)this;
	}

	public java.lang.String getTeacherName() {
		return getStr("teacher_name");
	}

	public M setClassAccount(java.lang.String classAccount) {
		set("class_account", classAccount);
		return (M)this;
	}

	public java.lang.String getClassAccount() {
		return getStr("class_account");
	}

	public M setClassPassword(java.lang.String classPassword) {
		set("class_password", classPassword);
		return (M)this;
	}

	public java.lang.String getClassPassword() {
		return getStr("class_password");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public M setSchoolId(java.lang.Integer schoolId) {
		set("school_id", schoolId);
		return (M)this;
	}

	public java.lang.Integer getSchoolId() {
		return getInt("school_id");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
