package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDeviceTransport<M extends BaseDeviceTransport<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setDeviceNumbers(java.lang.String deviceNumbers) {
		set("device_numbers", deviceNumbers);
		return (M)this;
	}

	public java.lang.String getDeviceNumbers() {
		return getStr("device_numbers");
	}

	public M setBillNumber(java.lang.String billNumber) {
		set("bill_number", billNumber);
		return (M)this;
	}

	public java.lang.String getBillNumber() {
		return getStr("bill_number");
	}

	public M setFrom1(java.lang.Integer from1) {
		set("from1", from1);
		return (M)this;
	}

	public java.lang.Integer getFrom1() {
		return getInt("from1");
	}

	public M setTo1(java.lang.Integer to1) {
		set("to1", to1);
		return (M)this;
	}

	public java.lang.Integer getTo1() {
		return getInt("to1");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
