package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMemberCopy<M extends BaseMemberCopy<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setNickname(java.lang.String nickname) {
		set("nickname", nickname);
		return (M)this;
	}

	public java.lang.String getNickname() {
		return getStr("nickname");
	}

	public M setOpenid(java.lang.String openid) {
		set("openid", openid);
		return (M)this;
	}

	public java.lang.String getOpenid() {
		return getStr("openid");
	}

	public M setAccountid(java.lang.Integer accountid) {
		set("accountid", accountid);
		return (M)this;
	}

	public java.lang.Integer getAccountid() {
		return getInt("accountid");
	}

	public M setSex(java.lang.String sex) {
		set("sex", sex);
		return (M)this;
	}

	public java.lang.String getSex() {
		return getStr("sex");
	}

	public M setCity(java.lang.String city) {
		set("city", city);
		return (M)this;
	}

	public java.lang.String getCity() {
		return getStr("city");
	}

	public M setProvince(java.lang.String province) {
		set("province", province);
		return (M)this;
	}

	public java.lang.String getProvince() {
		return getStr("province");
	}

	public M setHeadimgurl(java.lang.String headimgurl) {
		set("headimgurl", headimgurl);
		return (M)this;
	}

	public java.lang.String getHeadimgurl() {
		return getStr("headimgurl");
	}

	public M setCreatedate(java.util.Date createdate) {
		set("createdate", createdate);
		return (M)this;
	}

	public java.util.Date getCreatedate() {
		return get("createdate");
	}

	public M setMobile(java.lang.String mobile) {
		set("mobile", mobile);
		return (M)this;
	}

	public java.lang.String getMobile() {
		return getStr("mobile");
	}

	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}

	public java.lang.Integer getType() {
		return getInt("type");
	}

	public M setTempname(java.lang.String tempname) {
		set("tempname", tempname);
		return (M)this;
	}

	public java.lang.String getTempname() {
		return getStr("tempname");
	}

	public M setAge(java.lang.Integer age) {
		set("age", age);
		return (M)this;
	}

	public java.lang.Integer getAge() {
		return getInt("age");
	}

	public M setMiniappOpenid(java.lang.String miniappOpenid) {
		set("miniapp_openid", miniappOpenid);
		return (M)this;
	}

	public java.lang.String getMiniappOpenid() {
		return getStr("miniapp_openid");
	}

	public M setUnionid(java.lang.String unionid) {
		set("unionid", unionid);
		return (M)this;
	}

	public java.lang.String getUnionid() {
		return getStr("unionid");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.Integer getStatus() {
		return getInt("status");
	}

}
