package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseClassStudent<M extends BaseClassStudent<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return getStr("name");
	}

	public M setEpalId(java.lang.String epalId) {
		set("epal_id", epalId);
		return (M)this;
	}

	public java.lang.String getEpalId() {
		return getStr("epal_id");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setStudentType(java.lang.Integer studentType) {
		set("student_type", studentType);
		return (M)this;
	}

	public java.lang.Integer getStudentType() {
		return getInt("student_type");
	}

	public M setSortId(java.lang.Integer sortId) {
		set("sort_id", sortId);
		return (M)this;
	}

	public java.lang.Integer getSortId() {
		return getInt("sort_id");
	}

	public M setIntegral(java.lang.Integer integral) {
		set("integral", integral);
		return (M)this;
	}

	public java.lang.Integer getIntegral() {
		return getInt("integral");
	}

	public M setContribution(java.lang.Integer contribution) {
		set("contribution", contribution);
		return (M)this;
	}

	public java.lang.Integer getContribution() {
		return getInt("contribution");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}

	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public M setMemberId(java.lang.Integer memberId) {
		set("member_id", memberId);
		return (M)this;
	}

	public java.lang.Integer getMemberId() {
		return getInt("member_id");
	}

	public M setDegreeOfDifficulty(java.lang.Float degreeOfDifficulty) {
		set("degree_of_difficulty", degreeOfDifficulty);
		return (M)this;
	}

	public java.lang.Float getDegreeOfDifficulty() {
		return getFloat("degree_of_difficulty");
	}

	public M setAvatar(java.lang.String avatar) {
		set("avatar", avatar);
		return (M)this;
	}

	public java.lang.String getAvatar() {
		return getStr("avatar");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public M setLessonIntegral(java.lang.Double lessonIntegral) {
		set("lesson_integral", lessonIntegral);
		return (M)this;
	}

	public java.lang.Double getLessonIntegral() {
		return getDouble("lesson_integral");
	}

	public M setAgentId(java.lang.Integer agentId) {
		set("agent_id", agentId);
		return (M)this;
	}

	public java.lang.Integer getAgentId() {
		return getInt("agent_id");
	}

	public M setSex(java.lang.Integer sex) {
		set("sex", sex);
		return (M)this;
	}

	public java.lang.Integer getSex() {
		return getInt("sex");
	}

	public M setBirthday(java.util.Date birthday) {
		set("birthday", birthday);
		return (M)this;
	}

	public java.util.Date getBirthday() {
		return get("birthday");
	}

}
