package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseClassRoomTemp<M extends BaseClassRoomTemp<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setTeacherId(java.lang.Integer teacherId) {
		set("teacher_id", teacherId);
		return (M)this;
	}

	public java.lang.Integer getTeacherId() {
		return getInt("teacher_id");
	}

	public M setTeacherName(java.lang.String teacherName) {
		set("teacher_name", teacherName);
		return (M)this;
	}

	public java.lang.String getTeacherName() {
		return getStr("teacher_name");
	}

	public M setClassName(java.lang.String className) {
		set("class_name", className);
		return (M)this;
	}

	public java.lang.String getClassName() {
		return getStr("class_name");
	}

	public M setCover(java.lang.String cover) {
		set("cover", cover);
		return (M)this;
	}

	public java.lang.String getCover() {
		return getStr("cover");
	}

	public M setSummary(java.lang.String summary) {
		set("summary", summary);
		return (M)this;
	}

	public java.lang.String getSummary() {
		return getStr("summary");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public M setSort(java.lang.Integer sort) {
		set("sort", sort);
		return (M)this;
	}

	public java.lang.Integer getSort() {
		return getInt("sort");
	}

	public M setCategoryId(java.lang.Integer categoryId) {
		set("category_id", categoryId);
		return (M)this;
	}

	public java.lang.Integer getCategoryId() {
		return getInt("category_id");
	}

	public M setBookResId(java.lang.Integer bookResId) {
		set("book_res_id", bookResId);
		return (M)this;
	}

	public java.lang.Integer getBookResId() {
		return getInt("book_res_id");
	}

	public M setGroupId(java.lang.String groupId) {
		set("group_id", groupId);
		return (M)this;
	}

	public java.lang.String getGroupId() {
		return getStr("group_id");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
