package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseFilecach<M extends BaseFilecach<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setEpalId(java.lang.String epalId) {
		set("epal_id", epalId);
		return (M)this;
	}

	public java.lang.String getEpalId() {
		return getStr("epal_id");
	}

	public M setDeviceNo(java.lang.String deviceNo) {
		set("device_no", deviceNo);
		return (M)this;
	}

	public java.lang.String getDeviceNo() {
		return getStr("device_no");
	}

	public M setPath(java.lang.String path) {
		set("path", path);
		return (M)this;
	}

	public java.lang.String getPath() {
		return getStr("path");
	}

	public M setCachData(java.lang.String cachData) {
		set("cach_data", cachData);
		return (M)this;
	}

	public java.lang.String getCachData() {
		return getStr("cach_data");
	}

	public M setInsertdate(java.lang.String insertdate) {
		set("insertdate", insertdate);
		return (M)this;
	}

	public java.lang.String getInsertdate() {
		return getStr("insertdate");
	}

	public M setUpdatedate(java.lang.String updatedate) {
		set("updatedate", updatedate);
		return (M)this;
	}

	public java.lang.String getUpdatedate() {
		return getStr("updatedate");
	}

}
