package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTSchool<M extends BaseTSchool<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setCodeS(java.lang.String codeS) {
		set("code_s", codeS);
		return (M)this;
	}

	public java.lang.String getCodeS() {
		return getStr("code_s");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return getStr("name");
	}

	public M setCodeA(java.lang.Integer codeA) {
		set("code_a", codeA);
		return (M)this;
	}

	public java.lang.Integer getCodeA() {
		return getInt("code_a");
	}

}
