package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseClassCourseReply<M extends BaseClassCourseReply<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setGradesId(java.lang.Integer gradesId) {
		set("grades_id", gradesId);
		return (M)this;
	}

	public java.lang.Integer getGradesId() {
		return getInt("grades_id");
	}

	public M setRecordId(java.lang.Integer recordId) {
		set("record_id", recordId);
		return (M)this;
	}

	public java.lang.Integer getRecordId() {
		return getInt("record_id");
	}

	public M setTeacherId(java.lang.Integer teacherId) {
		set("teacher_id", teacherId);
		return (M)this;
	}

	public java.lang.Integer getTeacherId() {
		return getInt("teacher_id");
	}

	public M setReplyText(java.lang.String replyText) {
		set("reply_text", replyText);
		return (M)this;
	}

	public java.lang.String getReplyText() {
		return getStr("reply_text");
	}

	public M setReplyVoice(java.lang.String replyVoice) {
		set("reply_voice", replyVoice);
		return (M)this;
	}

	public java.lang.String getReplyVoice() {
		return getStr("reply_voice");
	}

	public M setStudentVoice(java.lang.String studentVoice) {
		set("student_voice", studentVoice);
		return (M)this;
	}

	public java.lang.String getStudentVoice() {
		return getStr("student_voice");
	}

	public M setReplyTime(java.util.Date replyTime) {
		set("reply_time", replyTime);
		return (M)this;
	}

	public java.util.Date getReplyTime() {
		return get("reply_time");
	}

}
