package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseLevelLogo<M extends BaseLevelLogo<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setLevelLogoName(java.lang.String levelLogoName) {
		set("level_logo_name", levelLogoName);
		return (M)this;
	}

	public java.lang.String getLevelLogoName() {
		return getStr("level_logo_name");
	}

	public M setLevelLogo(java.lang.String levelLogo) {
		set("level_logo", levelLogo);
		return (M)this;
	}

	public java.lang.String getLevelLogo() {
		return getStr("level_logo");
	}

	public M setEditTime(java.util.Date editTime) {
		set("edit_time", editTime);
		return (M)this;
	}

	public java.util.Date getEditTime() {
		return get("edit_time");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
