package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBookorderinfo<M extends BaseBookorderinfo<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setBarcode(java.lang.String barcode) {
		set("barcode", barcode);
		return (M)this;
	}

	public java.lang.String getBarcode() {
		return getStr("barcode");
	}

	public M setOrderid(java.lang.Integer orderid) {
		set("orderid", orderid);
		return (M)this;
	}

	public java.lang.Integer getOrderid() {
		return getInt("orderid");
	}

	public M setCateid(java.lang.String cateid) {
		set("cateid", cateid);
		return (M)this;
	}

	public java.lang.String getCateid() {
		return getStr("cateid");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public M setCreatedate(java.util.Date createdate) {
		set("createdate", createdate);
		return (M)this;
	}

	public java.util.Date getCreatedate() {
		return get("createdate");
	}

}
