package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseClassCourseRankingCategory<M extends BaseClassCourseRankingCategory<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return getStr("name");
	}

	public M setStartTime(java.lang.String startTime) {
		set("start_time", startTime);
		return (M)this;
	}

	public java.lang.String getStartTime() {
		return getStr("start_time");
	}

	public M setEndTime(java.lang.String endTime) {
		set("end_time", endTime);
		return (M)this;
	}

	public java.lang.String getEndTime() {
		return getStr("end_time");
	}

	public M setClassGradesIds(java.lang.String classGradesIds) {
		set("class_grades_ids", classGradesIds);
		return (M)this;
	}

	public java.lang.String getClassGradesIds() {
		return getStr("class_grades_ids");
	}

}
