package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCoursePeriod<M extends BaseCoursePeriod<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setCourseId(java.lang.Integer courseId) {
		set("course_id", courseId);
		return (M)this;
	}

	public java.lang.Integer getCourseId() {
		return getInt("course_id");
	}

	public M setCourseperiodName(java.lang.String courseperiodName) {
		set("courseperiod_name", courseperiodName);
		return (M)this;
	}

	public java.lang.String getCourseperiodName() {
		return getStr("courseperiod_name");
	}

	public M setMissionCmdList(java.lang.String missionCmdList) {
		set("missionCmdList", missionCmdList);
		return (M)this;
	}

	public java.lang.String getMissionCmdList() {
		return getStr("missionCmdList");
	}

}
