package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseVideoVote<M extends BaseVideoVote<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setMemberId(java.lang.Integer memberId) {
		set("member_id", memberId);
		return (M)this;
	}

	public java.lang.Integer getMemberId() {
		return getInt("member_id");
	}

	public M setVid(java.lang.Integer vid) {
		set("vid", vid);
		return (M)this;
	}

	public java.lang.Integer getVid() {
		return getInt("vid");
	}

	public M setVoteDate(java.lang.Integer voteDate) {
		set("vote_date", voteDate);
		return (M)this;
	}

	public java.lang.Integer getVoteDate() {
		return getInt("vote_date");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
