package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSoundCollection<M extends BaseSoundCollection<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setSoundId(java.lang.String soundId) {
		set("sound_id", soundId);
		return (M)this;
	}

	public java.lang.String getSoundId() {
		return getStr("sound_id");
	}

	public M setImage(java.lang.String image) {
		set("image", image);
		return (M)this;
	}

	public java.lang.String getImage() {
		return getStr("image");
	}

	public M setSoundUrl(java.lang.String soundUrl) {
		set("sound_url", soundUrl);
		return (M)this;
	}

	public java.lang.String getSoundUrl() {
		return getStr("sound_url");
	}

	public M setSoundName(java.lang.String soundName) {
		set("sound_name", soundName);
		return (M)this;
	}

	public java.lang.String getSoundName() {
		return getStr("sound_name");
	}

	public M setSerierName(java.lang.String serierName) {
		set("serier_name", serierName);
		return (M)this;
	}

	public java.lang.String getSerierName() {
		return getStr("serier_name");
	}

	public M setIsbn(java.lang.String isbn) {
		set("isbn", isbn);
		return (M)this;
	}

	public java.lang.String getIsbn() {
		return getStr("isbn");
	}

	public M setUserId(java.lang.String userId) {
		set("user_id", userId);
		return (M)this;
	}

	public java.lang.String getUserId() {
		return getStr("user_id");
	}

	public M setInsertDate(java.util.Date insertDate) {
		set("insert_date", insertDate);
		return (M)this;
	}

	public java.util.Date getInsertDate() {
		return get("insert_date");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.Integer getStatus() {
		return getInt("status");
	}

}
