package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseQiniuFileLog<M extends BaseQiniuFileLog<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setFileUrl(java.lang.String fileUrl) {
		set("file_url", fileUrl);
		return (M)this;
	}

	public java.lang.String getFileUrl() {
		return getStr("file_url");
	}

	public M setAccessTime(java.util.Date accessTime) {
		set("access_time", accessTime);
		return (M)this;
	}

	public java.util.Date getAccessTime() {
		return get("access_time");
	}

}
