package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseLibraryProduct<M extends BaseLibraryProduct<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setMallProductId(java.lang.Integer mallProductId) {
		set("mall_product_id", mallProductId);
		return (M)this;
	}

	public java.lang.Integer getMallProductId() {
		return getInt("mall_product_id");
	}

	public M setLibraryId(java.lang.Integer libraryId) {
		set("library_id", libraryId);
		return (M)this;
	}

	public java.lang.Integer getLibraryId() {
		return getInt("library_id");
	}

}
