package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSoundSearch<M extends BaseSoundSearch<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setSoundName(java.lang.String soundName) {
		set("soundName", soundName);
		return (M)this;
	}

	public java.lang.String getSoundName() {
		return getStr("soundName");
	}

	public M setInsertDate(java.lang.String insertDate) {
		set("insertDate", insertDate);
		return (M)this;
	}

	public java.lang.String getInsertDate() {
		return getStr("insertDate");
	}

	public M setUserName(java.lang.String userName) {
		set("userName", userName);
		return (M)this;
	}

	public java.lang.String getUserName() {
		return getStr("userName");
	}

	public M setPage(java.lang.String page) {
		set("page", page);
		return (M)this;
	}

	public java.lang.String getPage() {
		return getStr("page");
	}

	public M setISBN(java.lang.String ISBN) {
		set("ISBN", ISBN);
		return (M)this;
	}

	public java.lang.String getISBN() {
		return getStr("ISBN");
	}

	public M setRemoteIP(java.lang.String remoteIP) {
		set("remoteIP", remoteIP);
		return (M)this;
	}

	public java.lang.String getRemoteIP() {
		return getStr("remoteIP");
	}

}
