package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMalllabel<M extends BaseMalllabel<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setLabelId(java.lang.Integer labelId) {
		set("labelId", labelId);
		return (M)this;
	}

	public java.lang.Integer getLabelId() {
		return getInt("labelId");
	}

	public M setIos(java.lang.Integer ios) {
		set("ios", ios);
		return (M)this;
	}

	public java.lang.Integer getIos() {
		return getInt("ios");
	}

	public M setWechat(java.lang.Integer wechat) {
		set("wechat", wechat);
		return (M)this;
	}

	public java.lang.Integer getWechat() {
		return getInt("wechat");
	}

	public M setAndroid(java.lang.Integer android) {
		set("android", android);
		return (M)this;
	}

	public java.lang.Integer getAndroid() {
		return getInt("android");
	}

}
