package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseIntegralLevleInfo<M extends BaseIntegralLevleInfo<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setLevleLogoId(java.lang.Integer levleLogoId) {
		set("levle_logo_id", levleLogoId);
		return (M)this;
	}

	public java.lang.Integer getLevleLogoId() {
		return getInt("levle_logo_id");
	}

	public M setLevel(java.lang.Integer level) {
		set("level", level);
		return (M)this;
	}

	public java.lang.Integer getLevel() {
		return getInt("level");
	}

	public M setIntegralStart(java.lang.Integer integralStart) {
		set("integral_start", integralStart);
		return (M)this;
	}

	public java.lang.Integer getIntegralStart() {
		return getInt("integral_start");
	}

	public M setIntegralEnd(java.lang.Integer integralEnd) {
		set("integral_end", integralEnd);
		return (M)this;
	}

	public java.lang.Integer getIntegralEnd() {
		return getInt("integral_end");
	}

}
