package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseLiveLesson<M extends BaseLiveLesson<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setLiveLessonId(java.lang.Integer liveLessonId) {
		set("live_lesson_id", liveLessonId);
		return (M)this;
	}

	public java.lang.Integer getLiveLessonId() {
		return getInt("live_lesson_id");
	}

	public M setLessonName(java.lang.String lessonName) {
		set("lesson_name", lessonName);
		return (M)this;
	}

	public java.lang.String getLessonName() {
		return getStr("lesson_name");
	}

	public M setAgentId(java.lang.Integer agentId) {
		set("agent_id", agentId);
		return (M)this;
	}

	public java.lang.Integer getAgentId() {
		return getInt("agent_id");
	}

	public M setLiveLessonGrade(java.lang.Integer liveLessonGrade) {
		set("live_lesson_grade", liveLessonGrade);
		return (M)this;
	}

	public java.lang.Integer getLiveLessonGrade() {
		return getInt("live_lesson_grade");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
