package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseClassroomPackageGrades<M extends BaseClassroomPackageGrades<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setPackId(java.lang.Integer packId) {
		set("pack_id", packId);
		return (M)this;
	}

	public java.lang.Integer getPackId() {
		return getInt("pack_id");
	}

	public M setGradesId(java.lang.Integer gradesId) {
		set("grades_id", gradesId);
		return (M)this;
	}

	public java.lang.Integer getGradesId() {
		return getInt("grades_id");
	}

}
