package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCourseCopy<M extends BaseCourseCopy<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return getStr("name");
	}

	public M setUrl(java.lang.String url) {
		set("url", url);
		return (M)this;
	}

	public java.lang.String getUrl() {
		return getStr("url");
	}

	public M setProductid(java.lang.Integer productid) {
		set("productid", productid);
		return (M)this;
	}

	public java.lang.Integer getProductid() {
		return getInt("productid");
	}

	public M setTotalClass(java.lang.Long totalClass) {
		set("total_class", totalClass);
		return (M)this;
	}

	public java.lang.Long getTotalClass() {
		return getLong("total_class");
	}

}
