package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCareSignIn<M extends BaseCareSignIn<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setStudentId(java.lang.Integer studentId) {
		set("student_id", studentId);
		return (M)this;
	}

	public java.lang.Integer getStudentId() {
		return getInt("student_id");
	}

	public M setYear(java.lang.Integer year) {
		set("year", year);
		return (M)this;
	}

	public java.lang.Integer getYear() {
		return getInt("year");
	}

	public M setWeek(java.lang.Integer week) {
		set("week", week);
		return (M)this;
	}

	public java.lang.Integer getWeek() {
		return getInt("week");
	}

	public M setDay(java.lang.Integer day) {
		set("day", day);
		return (M)this;
	}

	public java.lang.Integer getDay() {
		return getInt("day");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
