package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseWellLesson<M extends BaseWellLesson<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setBespeakId(java.lang.String bespeakId) {
		set("bespeak_id", bespeakId);
		return (M)this;
	}

	public java.lang.String getBespeakId() {
		return getStr("bespeak_id");
	}

	public M setClassTime(java.lang.String classTime) {
		set("class_time", classTime);
		return (M)this;
	}

	public java.lang.String getClassTime() {
		return getStr("class_time");
	}

	public M setTeacherId(java.lang.String teacherId) {
		set("teacher_id", teacherId);
		return (M)this;
	}

	public java.lang.String getTeacherId() {
		return getStr("teacher_id");
	}

	public M setSchoolName(java.lang.String schoolName) {
		set("school_name", schoolName);
		return (M)this;
	}

	public java.lang.String getSchoolName() {
		return getStr("school_name");
	}

	public M setClassName(java.lang.String className) {
		set("class_name", className);
		return (M)this;
	}

	public java.lang.String getClassName() {
		return getStr("class_name");
	}

	public M setChineseTeacherName(java.lang.String chineseTeacherName) {
		set("chinese_teacher_name", chineseTeacherName);
		return (M)this;
	}

	public java.lang.String getChineseTeacherName() {
		return getStr("chinese_teacher_name");
	}

	public M setPackageName(java.lang.String packageName) {
		set("package_name", packageName);
		return (M)this;
	}

	public java.lang.String getPackageName() {
		return getStr("package_name");
	}

	public M setBookName(java.lang.String bookName) {
		set("book_name", bookName);
		return (M)this;
	}

	public java.lang.String getBookName() {
		return getStr("book_name");
	}

	public M setBookId(java.lang.Integer bookId) {
		set("book_id", bookId);
		return (M)this;
	}

	public java.lang.Integer getBookId() {
		return getInt("book_id");
	}

	public M setStateSchoolId(java.lang.String stateSchoolId) {
		set("state_school_id", stateSchoolId);
		return (M)this;
	}

	public java.lang.String getStateSchoolId() {
		return getStr("state_school_id");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public M setLessonFrom(java.lang.String lessonFrom) {
		set("lesson_from", lessonFrom);
		return (M)this;
	}

	public java.lang.String getLessonFrom() {
		return getStr("lesson_from");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
