package com.wechat.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseLessonScriptReplyGroupRel<M extends BaseLessonScriptReplyGroupRel<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setLessonScriptReplyGroupId(java.lang.Integer lessonScriptReplyGroupId) {
		set("lesson_script_reply_group_id", lessonScriptReplyGroupId);
		return (M)this;
	}

	public java.lang.Integer getLessonScriptReplyGroupId() {
		return getInt("lesson_script_reply_group_id");
	}

	public M setLessonScriptReplyId(java.lang.Integer lessonScriptReplyId) {
		set("lesson_script_reply_id", lessonScriptReplyId);
		return (M)this;
	}

	public java.lang.Integer getLessonScriptReplyId() {
		return getInt("lesson_script_reply_id");
	}

}
